// Mapeamento de IDs de categorias para nomes de assuntos
// Gerado a partir de relatorio_assuntos.csv (apenas ativos)

export const categoriasMap: Record<string, string> = {
  "10": "Financeiro - Negociação de IP estático",
  "11": "Reclamação de Serviços",
  "13": "Interesse em Fibra Óptica",
  "15": "Processo de Desconto",
  "18": "Venda de Serviços Voip",
  "23": "Rede D-Kiros Internert - Manutenção de POP",
  "28": "Mudança de Tecnologia",
  "35": "Externo - Retirada de equipamento (cancelamento)",
  "38": "Comercial - Pós-venda (Instalação)",
  "39": "Emitir Contrato de Upgrade",
  "51": "Financeiro - Comprovante de Pagamento",
  "54": "Financeiro - Acompanhar pagamento",
  "55": "Financeiro - Boleto atualizado",
  "56": "Financeiro - Cheque",
  "57": "Financeiro - Emissão de boletos",
  "58": "Incluir no SPC",
  "59": "Emitir Contrato de Vendas",
  "60": "Retorno de Negociação",
  "61": "Ligacao para Lembrete / Cobranca / Aviso",
  "62": "Cobrança - Negociação Bemtevi 2015",
  "63": "Cobrança - Negociação de inadimplência",
  "64": "Cobrança - Negociação GCP",
  "65": "Nota Fiscal",
  "66": "Financeiro - Pagamento duplicado",
  "67": "Financeiro - Negociação de ponto de repetição",
  "68": "Reverter Cancelamento",
  "69": "Automatizada",
  "72": "Rede D-Kiros - instalação de equipamento em POP's",
  "73": "Retirada de equipamentos (Migração)",
  "77": "Comercial - Ligar/Retornar",
  "78": "Assuntos Internos - Colaboradores",
  "81": "Verificar Viabilidade",
  "82": "Financeiro - Emissão de contratos (TORRE)",
  "85": "Comercial - IP Fixo (estático)",
  "86": "Externo - Manutenção no cabeamento",
  "87": "Mudança de endereço - Instalação",
  "88": "Mudança de endereço - Retirada",
  "89": "Financeiro - Mudança de titularidade",
  "90": "Financeiro - Mudança de vencimento",
  "94": "Externo - Troca de cômodo",
  "100": "Instalação Fibra Óptica",
  "102": "Definir setor de viabilidade",
  "103": "Sem internet por falta de pagamento",
  "104": "Comercial - Agendamento Instalação",
  "106": "Bloquear Contrato",
  "107": "Financeiro - Outros/SPC",
  "108": "Financeiro - Emissão de boletos pós manutenção",
  "109": "SAC - Solicitação de cancelamento",
  "110": "Confirmação de cancelamento",
  "111": "Financeiro - Dúvidas financeiras",
  "112": "Financeiro - Solicitação de débito automático",
  "113": "Financeiro - Confirmação de débito automático",
  "114": "Comercial - Elogio do cliente",
  "116": "Financeiro - Central do Assinante",
  "117": "Atendimento - Atualização de cadastro",
  "118": "Financeiro - Permuta de serviços",
  "119": "Correção indicada pelo cliente",
  "120": "Retrabalho Chamado Técnico NPS",
  "121": "Financeiro - Venda de cabo de rede",
  "123": "Excluir no SPC",
  "126": "Cancelamento de IP Fixo",
  "127": "Degustação (upgrade e downgrade)",
  "128": "Chamado Técnico NPS",
  "129": "CRT - Pós Pesquisa Manutenção/Falha",
  "130": "Financeiro em Atraso",
  "131": "CAT - NPS",
  "134": "INFRA - Falha rede D-kiros",
  "135": "CRT - Pós Pesquisa Sem conexão",
  "137": "CRT - Pós Pesquisa Lentidão",
  "138": "CRT - Pesquisa NPS",
  "139": "CRT - Pós Pesquisa Quedas",
  "140": "Incluir IP Fixo",
  "141": "CRT - Pós Pesquisa Assistência",
  "142": "CRT - Pós Pesquisa Telefonia VOIP",
  "143": "Aditivo de Contrato",
  "145": "Financeiro - Pagseguro",
  "146": "CAT - Pesquisa NPS",
  "147": "Externo - Troca de equipamento para melhoria de sinal",
  "148": "Externo - Troca de antena para torre nova",
  "149": "CRT - Pós Pesquisa Preventivo",
  "151": "Liberação de acesso",
  "156": "INATIVO --- Cobrança - Ligação cobrança",
  "157": "CRT - Pesquisa de atendimento",
  "162": "Externo - Retirada de equipamentos de POP",
  "163": "Mudança de titularidade",
  "164": "Externo - Reinstalação de equipamentos",
  "166": "Entrega de carnê",
  "168": "INATIVO --- Externo - Cobrança externa",
  "169": "Assuntos Financeiros",
  "171": "Financeiro - Pagamento não encontrado",
  "173": "Pagamento Cancelado",
  "175": "Externo - troca de equipamentos para padronização do pop",
  "176": "SAC - Pesquisa de Satisfação",
  "177": "Comercial - Sem viabilidade do sinal",
  "178": "PÓS PESQUISA N2 - CRT",
  "179": "PÓS PESQUISA UPCALL - CRT",
  "180": "Inconsistência Cadastral (inutilizado)",
  "181": "Atendimento Belluno",
  "182": "Adesão ao Contrato 2017",
  "183": "Atendimento Inicial",
  "184": "Financeiro - Débito Automático (Inconsistência)",
  "185": "Financeiro - Alteração de forma de recebimento de faturas",
  "186": "INATIVO -- Cobrança - Cancelamento/Inadimplência",
  "187": "Mudança de Plano - Upgrade",
  "188": "Mudança de Plano - Downgrade",
  "189": "Agendamento de horário",
  "190": "Rede D-Kiros - Projeto novo",
  "191": "Comercial - Levantamento de Demanda de Cliente",
  "192": "Estoque - Levantamento de Equipamentos",
  "193": "MANUTENÇÃO/FALHA - CRT",
  "194": "Financeiro - Avaliar Viabilidade Financeira do Projeto",
  "195": "Comercial - Libera Comercial para Vendas",
  "196": "Financeiro - Envio de boleto",
  "197": "Comercial - Pós venda",
  "198": "RETRABALHO MANUTENÇÃO/FALHA - CRT",
  "199": "Envio de Formulario de Portabilidade Voip",
  "200": "Comercial - Solicitar assinatura nos Termos",
  "201": "PESQUISA PÓS ATENDIMENTO MANUTENÇÃO/FALHA",
  "202": "Externo - Visita de viabilidade",
  "203": "Comercial - Viabilidade negada",
  "204": "Comercial - Cadastro Prospecção",
  "205": "Comercial - Consulta no SPC",
  "206": "Comercial - Retornar para fechar venda",
  "207": "Comercial - Completa Cadastro do Cliente",
  "208": "Estoque - Separar Equipamentos da instalação",
  "210": "Vender Produtos",
  "211": "Chamado técnico",
  "213": "Desenvolvimento e Parametrização",
  "215": "CANCELAMENTO",
  "216": "Cobrança (valores em aberto/produtos)",
  "219": "Faturar venda de produtos",
  "221": "Retorno de Viabilidade",
  "222": "REGISTRO DE ATENDIMENTO GERAL",
  "223": "INATIVO --- Mudança de endereço",
  "224": "INATIVO - TROCA DE PLANO",
  "225": "INATIVO - TROCA DE TITULARIDADE",
  "226": "INATIVO --- TROCA DE VENCIMENTO",
  "227": "INATVO - Venda Residencial",
  "228": "EMPRESARIAL- VENDA",
  "235": "Bloqueio Temporário",
  "237": "Suporte Avançado (Nivel 2)",
  "238": "Comercial - Informações sobre endereço D-Kiros",
  "240": "Pós venda - Sem contato",
  "241": "Transferencia de endereço",
  "243": "Instalação Via Radio",
  "254": "UPGRADE INTERNET",
  "256": "Manutenção Preventiva - Operacional",
  "257": "Oferta - Upgrade",
  "258": "Cancelar Financeiro",
  "260": "Externo - Retirada de equipamento (inadimplência)",
  "261": "CRT - Teste Conexão",
  "264": "Renovação - Assinatura no Contrato",
  "265": "Divergência Financeira",
  "266": "Débito Automático (Nova Remessa)",
  "267": "Auditoria de Manutenção",
  "268": "PROCON",
  "269": "O Multiplicador- Promoção",
  "270": "INATIVO - Visita Técnica de Viabilidade",
  "271": "Viabilidade reprovada",
  "272": "Viabilidade aprovada",
  "273": "Auditoria de Instalação",
  "274": "Faturamento Instalação",
  "276": "CRT - Mudança de titularidade",
  "277": "Regulagem de Sinal na fibra",
  "278": "CRT - Alteração WIFI",
  "279": "Aguardando Assinatura (Pós- Ativação)",
  "280": "Alinhamento de Informações",
  "281": "Mapeamento da rede",
  "282": "Passagem de Cabo",
  "283": "Serviços Gerais",
  "284": "Instalação de Equipamentos",
  "285": "Parceira - Eventos/Ações",
  "286": "VOIP novo cliente",
  "287": "Instalar Voip",
  "288": "Retorno de Degustação",
  "289": "VOIP - Telefonia",
  "290": "INTIMAÇÃO",
  "291": "Ativação de cliente fibra",
  "292": "CRT - NPS",
  "293": "Retorno de Portabilidade",
  "294": "Notificação Extrajudicial / Processos",
  "296": "Readequação de rede",
  "297": "CRT - Assistência",
  "298": "Emitir contrato de Downgrade",
  "299": "Retirada - Desconectar Fast Conector da CTO",
  "300": "VOIP - Configuração VOIP",
  "301": "CRT - Telefonia VOIP",
  "302": "CRT - Auditoria de atendimento",
  "304": "Externo - VOIP - Configuração PABX",
  "306": "CRT - Retrabalho Assistência",
  "307": "CRT - Retrabalho Telefonia VOIP",
  "308": "CRT - Retrabalho Sem Conexão",
  "309": "CRT - Retrabalho Quedas de conexão",
  "310": "CRT - Retrabalho Lentidão",
  "311": "CRT - Sem Conexão",
  "312": "CRT - Quedas de conexão",
  "313": "CRT - Retrabalho Preventivo",
  "315": "CAT - Problema em cabeamento externo (INFRA)",
  "316": "Retrabalho Chamado técnico",
  "317": "Retrabalho Chamado técnico - Preventivo",
  "318": "Instalação Novo Ponto",
  "319": "CRT - Lentidão",
  "320": "CAT - Pesquisa de Manutenção",
  "321": "Troca de Titularidade - Confirmação de cancelamento",
  "322": "Reverter Cancelamento VOIP",
  "323": "Confirmação de cancelamento VOIP",
  "324": "Retirada de equipamento VOIP (cancelamento)",
  "325": "Desativar contratos VOIP",
  "326": "Processo- Upsupport - {Upcall}",
  "327": "Triagem de Suporte",
  "328": "Suporte Nível 3",
  "329": "SUPORTE NIVEL 1",
  "330": "Pesquisa pós suporte",
  "331": "Suporte Nível 2",
  "332": "Auditoria de Suporte",
  "333": "Retrabalho Chamado Técnico",
  "334": "Faturar Suporte",
  "335": "Revisão Financeira",
  "336": "Retorno de orçamento VOIP",
  "337": "Comercial - Ligar/Retornar - Upcall",
  "338": "Upgrade - Faturamento",
  "339": "Faturamento - Titularidade",
  "340": "Acionamento - Manutenção de Infraestrutura",
  "341": "Downgrade - Faturamento",
  "342": "AUDITORIA DE ATENDIMENTO",
  "343": "Processo De Ativação - Upgradeisp",
  "348": "Revisão Financeira - Ativação",
  "355": "AUDITORIA UPCALL",
  "357": "Processo de Suporte Fibra / Rádio",
  "358": "Suporte Nível 1",
  "359": "Fibra - Suporte Nível 2",
  "360": "Fibra - Suporte Externo",
  "361": "Fibra - Auditoria Técnica de Suporte",
  "362": "Fibra - Retrabalho Técnico",
  "363": "Fibra - Pesquisa Pós Suporte",
  "364": "Faturar Manutenção",
  "365": "Rádio - Suporte Nível 2",
  "366": "Rádio - Suporte Externo",
  "367": "Rádio - Auditoria Técnica de Suporte",
  "368": "Rádio - Retrabalho Técnico",
  "369": "Rádio - Pesquisa Pós Suporte",
  "370": "Faturar Suporte",
  "371": "Processo de Ativação Fibra / Rádio",
  "372": "Solicitar Venda",
  "373": "Confirmar Ativação",
  "374": "Retrabalho de Venda",
  "375": "Desistir Pré-Contrato",
  "376": "Ativar Internet (Fibra)",
  "377": "Fibra - Falha na Ativação",
  "378": "Auditar Ativação",
  "379": "Viabilidade somente Rádio",
  "380": "Fibra - Verificação de Viabilidade",
  "381": "Retrabalho de Ativação",
  "382": "Faturar Ativação",
  "383": "Pesquisar Pós Ativação",
  "384": "Rádio - Auditoria da Solicitação",
  "385": "Rádio - Retrabalho de Venda",
  "386": "Ativar Internet (Rádio)",
  "388": "Rádio - Falha na Ativação",
  "389": "Rádio - Auditoria Técnica da Ativação",
  "390": "Rádio - Verificação de Viabilidade",
  "391": "Rádio - Retrabalho Técnico de Ativação",
  "392": "Faturar Ativação (Rádio)",
  "393": "Desconto de reversão de cancelamento",
  "394": "Retrabalho de Confirmação",
  "395": "Rádio - Retrabalho de Contrato",
  "396": "Processo de Consulta de Viabilidade/SPC",
  "397": "Solicitar Consulta",
  "398": "Consultar SPC",
  "399": "Retorno de Consulta SPC",
  "400": "Faturar Taxa de Ativação",
  "401": "Consultar Viabilidade",
  "402": "Retorno de Viabilidade",
  "403": "Confirmar Viabilidade",
  "405": "Retorno de Viabilidade Campo",
  "406": "Reter Cliente",
  "407": "Retirada de carnê no escritório",
  "408": "Auditoria de retirada dos equipamentos",
  "411": "Solicitação de Mudança de Endereço",
  "412": "Rádio - Auditoria da Solicitação - Mudança de Endereço",
  "413": "Rádio - Mudança de Endereço",
  "414": "Rádio - Auditoria da Mudança de End.",
  "415": "Rádio - Falha na Mudança de Endereço",
  "416": "Revisão / Faturamento - Mudança de Endereço",
  "417": "Rádio - Nova Tentativa de Mudança",
  "418": "Pesquisa Pós Mudança de Endereço",
  "419": "Cancelamento por Inviabilidade",
  "420": "Rádio - Retrabalho de Auditoria",
  "421": "Retrabalho da Solicitação",
  "422": "INATIVO -- Processo de Alteração de Plano",
  "423": "Solicitar Alteração de Plano",
  "424": "Confirmar Alteração de Plano",
  "425": "Trocar Equipamentos",
  "426": "Pesquisa Pós Alteração de Plano",
  "428": "Correção de comodato",
  "429": "Venda de produtos (Interno)",
  "430": "Auditoria Técnica de Suporte",
  "431": "Falha na Troca do Equipamento",
  "432": "Faturar Alteração de Plano",
  "433": "Retrabalho de Troca",
  "434": "Nova Tentativa de Troca de Equipamento",
  "435": "Reter Alteração de Plano",
  "436": "Cancelar Alteração de Plano",
  "437": "Retrabalho de Solicitação",
  "438": "CRT - Período de Degustação",
  "439": "CGR - Alterações IP Fixo (estático)",
  "440": "CGR - Inclusão IP Fixo (estático)",
  "441": "INATIVO -- Processo de Migração de Tecnologia",
  "442": "Solicitação de Migração",
  "443": "Confirmar Migração",
  "444": "Retrabalho da Solicitação - Migração",
  "445": "Cancelamento de Contrato - Migração",
  "446": "Migração - Ativação Técnica",
  "447": "Retirada de Equipamentos - Migração",
  "448": "Auditoria da Migração",
  "449": "Auditoria Técnica de Retirada",
  "450": "Falha na Migração",
  "451": "Retrabalho Técnico da Migração",
  "452": "Faturar Migração",
  "454": "Retrabalho de Confirmação - Mudança de Tecnologia",
  "455": "Retrabalho de Retirada - Alteração de Plano",
  "456": "Cobrar Equipamentos - Migração",
  "457": "Faturar Equipamentos - Migração",
  "458": "Retrabalho de Retirada de Equipamentos - Migração",
  "459": "Pesquisa Pós Migração",
  "460": "CRT - Inclusão degustação",
  "461": "Fibra - Auditoria da Solicitação - Mudança de Endereço",
  "462": "Fibra - Mudança de Endereço",
  "463": "Fibra - Auditoria da Mudança de End.",
  "464": "Fibra - Falha na Mudança de Endereço",
  "465": "Fibra - Faturamento de Mudança de Endereço",
  "466": "Fibra - Nova Tentativa de Mudança",
  "467": "Fibra - Retrabalho Técnico - Mudança de Endereço",
  "468": "Remoção do Conector - Mudança de Endereço",
  "469": "Retirada de Equipamento(s) - Mudança de Endereço",
  "470": "Auditoria de Retirada do(s) Equip.",
  "471": "Cobrar Equipamentos - Mudança de Endereço",
  "472": "Faturar Equipamentos - Mudança de Endereço",
  "473": "Cancelamento De Pré-Cadastro - Mudança de Endereço",
  "474": "Viável apenas em Rádio",
  "475": "Fibra - Retrabalho de Auditoria - Mudança de Endereço",
  "476": "Retrabalho de Retirada de Equipamentos - Mudança de Endereço",
  "477": "Revisar financeiro",
  "478": "Negativar Contrato - Inclusão no SPC",
  "479": "Retrabalho Técnico de Mudança de Endereço",
  "480": "Auditoria Pós Devolução de Comodato",
  "481": "CRT - Liberação de contrato",
  "482": "Chamado técnico - Preventivo",
  "483": "Confirmação de cancelamento IP Fixo",
  "484": "Análise de Viabilidade de Velocidade",
  "485": "Alteração de Plano",
  "486": "Cancelamento da Solicitação - Alteração de Plano",
  "487": "Faturamento da Alteração de Plano",
  "488": "Auditar Mudança de Endereço e Tecnologia",
  "489": "Solicitação de Cancelamento - Mudança de Endereço",
  "490": "Retirada da Antena - Mudança de Endereço",
  "491": "Auditoria Pós Retirada da Antena",
  "492": "Executar Processo - Migração",
  "493": "Retrabalho de Auditoria - Mudança de Tecnologia",
  "494": "Solicitar Telefonia",
  "495": "TEL - Confirmar Ativação (Portabilidade)",
  "496": "TEL - Confirmar Ativação (Número Novo)",
  "497": "TEL - Configurar Linha SIP",
  "498": "TEL - Faturar Ativação (Portabilidade)",
  "499": "TEL - Faturar Ativação (Número Novo)",
  "500": "TEL - Instalação de Telefonia (Portabilidade)",
  "501": "TEL - Instalação de Telefonia (Número Novo)",
  "502": "TEL - Retrabalho de Instalação (Portabilidade)",
  "503": "TEL - Retrabalho de Instalação (Número Novo)",
  "504": "Processo de Telefonia Digital",
  "505": "TEL - Retrabalho de Solicitação",
  "506": "TEL - Auditoria de Instalação (Portabilidade)",
  "507": "TEL - Auditoria de Instalação (Número Novo)",
  "508": "TEL - Pesquisa Pós Ativação",
  "509": "Processo de Troca de Titularidade",
  "510": "Solicitar Troca de Titularidade",
  "511": "Confirmar Troca de Titularidade",
  "512": "Faturar Troca de Titularidade",
  "513": "Pesquisa Pós Troca de Titularidade",
  "514": "Cobrar Equipamentos - Troca de Titularidade",
  "515": "Faturar Equipamentos - Troca de Titularidade",
  "516": "Retrabalho de Solicitação - Troca de Titularidade",
  "517": "Cancelar Troca de Titularidade",
  "518": "Cobrar Novo Titular",
  "519": "Faturar Inadimplência - Troca de Titularidade",
  "520": "Receber Pagamento - Troca de Titularidade",
  "521": "Confirmar Assinatura - Troca de Titularidade",
  "522": "Auditar Cobrança - Troca de Titularidade",
  "523": "Processo de Suspensão Temporária",
  "524": "Solicitar Suspensão Temporária",
  "525": "Confirmar Suspensão Temporária",
  "526": "Retrabalho de Solicitação - Suspensão Temporária",
  "527": "Solicitar Liberação de Acesso",
  "528": "Confirmar Liberação de Acesso",
  "529": "Retrabalho de Solicitação - Liberação de Acesso",
  "530": "Processo de Liberação de Acesso",
  "531": "Processo de Débito Automático",
  "532": "Solicitar Débito Automático",
  "533": "Processo de Cancelamento de Telefonia",
  "534": "TEL - Solicitar Cancelamento de Telefonia",
  "535": "TEL - Reverter Cancelamento",
  "536": "TEL - Confirmar Cancelamento",
  "537": "TEL - Retrabalho de Reversão",
  "538": "TEL - Faturar Cancelamento",
  "539": "TEL - Auditar Cancelamento",
  "540": "TEL - Retrabalho de Cancelamento",
  "541": "TEL - Retrabalho de Faturamento - Cancelamento",
  "542": "TEL - Incluir no SPC",
  "543": "TEL - Negativar Contrato",
  "544": "TEL - Retirada de Equipamentos",
  "545": "TEL - Auditoria de Retirada",
  "546": "TEL - Retrabalho de Retirada",
  "547": "TEL - Cobrança de Equipamentos",
  "548": "TEL - Faturar Equipamentos",
  "549": "TEL - Retrabalho de Cobrança - Cancelamento",
  "550": "TEL - Nova Tentativa de Retirada",
  "551": "TEL - Desativar Contrato",
  "552": "Processo de Cobrança",
  "553": "Visita Técnica - Cobrança",
  "554": "Auditar Visita - Cobrança",
  "555": "Retrabalho de Visita - Cobrança",
  "556": "Retirada de Equipamentos - Cobrança",
  "557": "Retrabalho Técnico - Cobrança",
  "558": "Retrabalho de Retirada - Cobrança",
  "559": "Retrabalho de Comprovante - Cobrança",
  "560": "Nova Tentativa de Visita Técnica - Cobrança",
  "561": "Nova Tentativa de Retirada - Cobrança",
  "562": "Negociar Inadimplência",
  "563": "Negativar Contrato - Cobrança",
  "564": "Incluir no SPC - Cobrança",
  "565": "X - Faturamento de Negociação",
  "566": "Faturamento de Inadimplência",
  "567": "Falha na Visita Técnica - Cobrança",
  "568": "X - Comprovante de Pagamento",
  "569": "Cobrança de Equipamentos",
  "570": "Auditoria Técnica - Cobrança",
  "571": "Auditoria de Retirada - Cobrança",
  "572": "Retrabalho de Auditoria - Renegociação",
  "573": "Faturar Negociação",
  "574": "Faturar Entrada - Cobrança",
  "575": "Processo de Cobrança",
  "576": "Renegociar Negociação",
  "577": "Processo de Indicação (O Multiplicador)",
  "578": "Indicação",
  "579": "Auditoria de Indicação",
  "580": "Negociar com Indicado",
  "581": "Ceder Desconto (Indicação)",
  "582": "Retorno da Indicação (Desconto)",
  "583": "Retrabalho de Indicação",
  "584": "Indicação Inválida",
  "585": "Rádio - Retrabalho Técnico - Mudança de Endereço",
  "586": "Contar Portas - Rede Neutra",
  "587": "Auditoria de serviços VOIP / PABX",
  "588": "Retrabalho de Confirmação - Troca de Titularidade",
  "589": "Faturar Portas - Rede Neutra",
  "590": "Passo 4 - Retirada",
  "591": "Passo 5 - Distrato",
  "592": "Faturar Cancelamento - Inadimplência",
  "593": "TEL - Faturar Cancelamento (Inadimplência)",
  "594": "Processo de Alteração de Plano - Telefonia",
  "595": "Solicitar Alteração de Plano do VoIP",
  "596": "TEL - Confirmar Alteração de Plano",
  "597": "TEL - Retrabalho de Solicitação - Alteração de Plano",
  "598": "Processo - Édimo Advocacia",
  "599": "EDM - Revisar Contrato",
  "600": "EDM - Acompanhar",
  "601": "EDM - Faturar Financeiro",
  "602": "EDM - Enviar Planilha",
  "603": "D-Cash - Campanha",
  "604": "Pagamento D-Cash",
  "606": "CRT - Retrabalho Reincidência Telefonia VOIP",
  "607": "CRT - Retrabalho Reincidencia Assistencia",
  "609": "CRT - Retrabalho Reincidencia Sem Conexão",
  "611": "CRT - Retrabalho Reincidencia Lentidão",
  "613": "CRT - Retrabalho Reincidência Quedas de Conexão",
  "615": "CRT - Retrabalho Reincidência Preventivo",
  "619": "AUDITORIA DE ATENDIMENTO UPCALL",
  "620": "PESQUISA PÓS ATENDIMENTO UPCALL",
  "621": "RETRABALHO TECNICO UPCALL",
  "622": "AUDITORIA DE ATENDIMENTO - CRT",
  "623": "PESQUISA PÓS ATENDIMENTO",
  "624": "RETRABALHO TECNICO N2 - CRT",
  "625": "PESQUISA PÓS SUPORTE",
  "626": "RETRABALHO TECNICO - SUPORTE EXTERNO",
  "627": "Chamado técnico Quedas de conexão",
  "628": "Retrabalho Chamado técnico Quedas de conexão",
  "629": "Chamado técnico Lentidão",
  "630": "Retrabalho Chamado técnico Lentidão",
  "631": "Chamado técnico Sem Conexão",
  "632": "Retrabalho Chamado técnico Sem Conexão",
  "633": "Chamado técnico Assistência",
  "634": "Retrabalho Chamado técnico Assistência",
  "635": "Chamado técnico Telefonia",
  "636": "Retrabalho Chamado técnico Telefonia",
  "637": "Chamado técnico Reincidência Telefonia VOIP",
  "638": "Retrabalho Chamado técnico Reincidência Telefonia",
  "639": "Chamado técnico Reincidência Assistência",
  "640": "Retrabalho Chamado técnico Reincidência Assistência",
  "641": "Chamado técnico Reincidência Sem Conexão",
  "642": "Retrabalho Chamado técnico Reincidência Sem Conexão",
  "643": "Chamado técnico Reincidência Lentidão",
  "644": "Retrabalho Chamado técnico Reincidência Lentidão",
  "645": "Chamado técnico Reincidência Quedas de conexão",
  "646": "Retrabalho Chamado técnico Reincidência Quedas de conexão",
  "647": "Chamado técnico Reincidência Preventivo",
  "648": "Retrabalho Chamado técnico Reincidência Preventivo",
  "649": "Confirmar Débito Automático",
  "650": "Retrabalho de Solicitação - Débito Automático",
  "651": "Gerar Boleto de Entrada - Débito Automático",
  "652": "Gerar Nova Remessa - Débito Automático",
  "653": "Processo de Nota Fiscal",
  "654": "Solicitar Nota Fiscal",
  "655": "Gerar NF - Atendimento",
  "656": "Retrabalho de Solicitação - Nota Fiscal",
  "657": "Processo Cancelamento de Telefonia por Inadimplência",
  "658": "TEL - Faturar Equipamentos",
  "659": "Telefonia - Retrabalho de Cobrança",
  "661": "(INATIVO) Processo de Mudança de Endereço",
  "662": "Auditoria de Remoção de CTO",
  "663": "Auditar Retirada - Mudança de Endereço",
  "664": "Auditar Mudança de Endereço",
  "665": "Reter Cliente - Mudança de Endereço",
  "666": "Cobrar Equipamentos - Mudança de Endereço",
  "667": "Faturar Equipamentos - Mudança de Endereço",
  "668": "Confirmar Mudança de Endereço",
  "669": "Mud Endereço - Executar Processo",
  "670": "Faturar Mudança de Endereço",
  "671": "Retrabalho de Confirmação - Mudança de Endereço",
  "672": "Mudar de Endereço",
  "673": "Mudança de Endereço (Rádio)",
  "674": "Remoção do Conector - Mudança de Endereço",
  "675": "Retirar Equipamentos - Mudança de Endereço",
  "676": "Retirada de Equipamentos (Rádio)",
  "677": "Retrabalho de Cobrança - Mudança de Endereço",
  "678": "Retrabalho de Retirada - Mudança de Endereço",
  "679": "Retrabalho de Solicitação - Mudança de Endereço",
  "680": "Retrabalho de Mudança",
  "681": "Solicitar Mudança de Endereço",
  "682": "Chamado técnico - CRT",
  "683": "Coletar Assinatura",
  "684": "Auditoria de Manutenção Correção de processo",
  "685": "Processo de Troca de Titularidade de Telefonia",
  "686": "TEL - Solicitar Troca de Titularidade",
  "687": "TEL - Retrabalho de Solicitação - Troca Titularidade",
  "688": "TEL - Consultar Consumo Excedente",
  "689": "TEL - Faturar Troca Titularidade",
  "690": "TEL - Confirmar Troca de Titularidade",
  "691": "TEL - Troca de Titularidade de Linha",
  "692": "TEL - Faturar Novo Titular",
  "693": "TEL - Visita Técnica - Troca Titularidade",
  "694": "TEL - Inativar Antigo Titular",
  "695": "TEL - Retrabalho de Confirmação - Troca Titularidade",
  "696": "TEL - Auditoria Técnica - Troca Titularidade",
  "697": "TEL - Retrabalho Técnico - Troca Titularidade",
  "698": "D-Cash - Validação de comissionamento",
  "699": "Confirmar Negociação - Cobrança",
  "700": "Retorno de Viabilidade (externo)",
  "701": "Configurar serviços adicionais Voip / PABX",
  "702": "Receber Pagamento - Cobrança",
  "703": "Auditar Inadimplência - Cobrança",
  "704": "Faturar Equipamentos - Cobrança",
  "706": "Cancelar Migração",
  "707": "Negociar com Indicado (Isenção)",
  "708": "Retorno da Indicação (Isenção)",
  "709": "Isentar Fidelidade (Indicação)",
  "710": "Telefonia - Consumo Excedente - Cancelamento",
  "711": "Telefonia - Retorno Excedente - Cancelamento",
  "712": "Analisar Contagem - Rede Neutra",
  "713": "Processo - Métrica Soluções",
  "714": "MET - Revisar Contrato",
  "715": "MET - Acompanhar",
  "716": "MET - Faturar Financeiro",
  "717": "MET - Enviar Planilha",
  "718": "Retorno de Excedente de Minutagem VOIP",
  "719": "Análise de Excedente de Minutagem VOIP",
  "720": "Processo de Cancelamento",
  "721": "Reversão de Cancelamento",
  "722": "Confirmar Cancelamento",
  "723": "Retrabalho de Reversão - Cancelamento",
  "724": "Faturar Cancelamento",
  "725": "Auditar Cancelamento",
  "726": "Retrabalho de Cancelamento",
  "727": "Retrabalho de Faturamento - Cancelamento",
  "728": "Incluir no SPC - Cancelamento",
  "729": "Negativar Contrato - Cancelamento",
  "730": "Retirada de Equipamentos - Cancelamento",
  "731": "Auditoria de Retirada - Cancelamento",
  "732": "Retrabalho de Retirada - Cancelamento",
  "733": "Cobrança de Equipamentos - Cancelamento",
  "734": "Faturar Equipamentos - Cancelamento",
  "735": "Retrabalho de Cobrança - Cancelamento",
  "736": "Nova Tentativa de Retirada - Cancelamento",
  "737": "Ceder Desconto (Reversão) - Cancelamento",
  "738": "Pesquisa Pós Retenção - Cancelamento",
  "739": "Suporte de Retenção - CRT - Cancelamento",
  "740": "Suporte de Retenção - Cancelamento",
  "741": "Auditoria Técnica de Suporte - Cancelamento",
  "742": "Retrabalho de Suporte - Cancelamento",
  "743": "Desativar Contrato - Cancelamento",
  "744": "Processo de Devolução da Métrica",
  "745": "MET - Solicitar Devolução",
  "746": "Solicitação de Contratação de Serviço Adicional",
  "747": "Contratar Rede Mesh",
  "748": "Retrabalho de Serviço Adicional",
  "749": "Instalar Rede Mesh",
  "750": "Faturamento de Rede Mesh",
  "751": "Processo de Exclusão no SPC",
  "752": "Processo de Inclusão no SPC",
  "753": "Auditar Pré-Negativação - Inclusão SPC",
  "754": "Retrabalho de Faturamento - Inclusão SPC",
  "755": "Auditoria Técnica - Serviços Adicionais",
  "756": "Processo de Portabilidade com Troca de Titularidade",
  "757": "TEL - Confirmar Portabilidade",
  "758": "Retrabalho de Solicitação - Portabilidade/TT",
  "759": "Configurar VoIP - Portabilidade/TT",
  "760": "Instalação de Telefonia - Portabilidade/TT",
  "761": "TEL - Faturar Portabilidade",
  "762": "Retrabalho de Confirmação - Portabilidade/TT",
  "763": "Solicitar Troca de Titularidade - Portabilidade",
  "764": "TEL - Auditoria de Instalação - Portabilidade/TT",
  "765": "Retrabalho de Instalação - Portabilidade/TT",
  "767": "MET - Receber Repasse",
  "768": "CRT - Manutenção/Falha",
  "769": "Chamado técnico - Manutenção/Falha",
  "770": "Retrabalho Chamado técnico - Manutenção/Falha",
  "771": "CRT - Retrabalho Manutenção/Falha",
  "772": "Auditoria de Infraestrutura",
  "773": "Negociação de Empreitada",
  "774": "Auditoria de Empreitada",
  "775": "Retrabalho de Empreitada",
  "776": "Passagem de Cabo",
  "777": "Auditoria de Passagem de Cabo",
  "778": "Retrabalho de Passagem de Cabo",
  "779": "Reverter Empreitada",
  "780": "Acompanhar Empreitada",
  "781": "Faturamento de Empreitada",
  "782": "Retrabalho de Contrato",
  "783": "Processo de Cancelamento por Inadimplência",
  "784": "Processo de Cancelamento de Telefonia por Inadimplência",
  "785": "Auditar Cancelamento - Inadimplência",
  "786": "Retrabalho de Faturamento - Inadimplência",
  "787": "Incluir no SPC - Inadimplência",
  "788": "Negativar Contrato - Inadimplência",
  "789": "Processo de Comprovante de Pagamento",
  "790": "Comprovante de Pagamento",
  "791": "Receber Pagamento - Comprovante",
  "792": "Retrabalho de Comprovante",
  "793": "Devolver Troca de Titularidade",
  "794": "Enviar Comprovante de Devolução",
  "795": "CS - Pesquisa pós atendimento CRT",
  "796": "CS - Pesquisa pós atendimento Upcall",
  "797": "Ativação de CTO / Ampliação de Portas",
  "798": "Renegociar Parcelamento - Inclusão SPC",
  "799": "Manutenção de Infraestrutura",
  "800": "Acompanhar Suspensão",
  "801": "Remover Suspensão",
  "802": "Remover Suspensão Antecipadamente",
  "803": "Entregar Carnê - Suspensão",
  "804": "Auditoria de Transferencia Upcall",
  "805": "Agendar visita tecnica - CRT",
  "806": "Boletim de Ocorrência - B.O.",
  "807": "CRT - Comercial",
  "808": "Processo Judicial",
  "809": "Faturar Taxa de Ativação",
  "810": "Coletar Assinatura - Vendas",
  "811": "Retrabalho de Auditoria - Ativação",
  "812": "Receber Pagamento - Ativação",
  "813": "Inviabilidade de Degustação",
  "814": "CRT - Link TV",
  "815": "CRT - TV Assistência",
  "816": "CRT - Retrabalho TV Assistência",
  "817": "CRT - Pós Pesquisa TV Assistência",
  "818": "Processo de Ativação (Televisão)",
  "819": "TV - Solicitar Ativação",
  "820": "TV - Confirmar Ativação",
  "821": "TV - Faturar Ativação",
  "822": "TV - Visita Técnica",
  "823": "TV - Cobrar Assinatura",
  "824": "Retrabalho de Solicitação - TV",
  "825": "TV - Auditar Visita",
  "826": "Retrabalho Técnico - TV",
  "827": "Retrabalho de Auditoria - TV",
  "828": "Retrabalho de Confirmação - TV",
  "829": "TV - Pesquisar Qualidade",
  "830": "Processo de Contratação de SVA",
  "831": "Solicitar SVA",
  "832": "Confirmar SVA",
  "833": "Faturar SVA",
  "834": "Retrabalho de Solicitação - SVA",
  "835": "Processo de Cancelamento de SVA",
  "836": "SVA - Solicitar Cancelamento",
  "837": "SVA - Confirmar Cancelamento",
  "838": "SVA - Reverter Cancelamento",
  "839": "SVA - Retrabalho de Reversão",
  "840": "SVA - Faturar Cancelamento",
  "841": "Cancelar Processo de Portabilidade",
  "842": "Receber Pagamento - Cancelamento por Inadimplência",
  "843": "Retrabalho de Recebimento - Cancelamento por Inadimplência",
  "844": "Processo de Alteração de Plano (Televisão)",
  "845": "TV - Solicitar Alteração de Plano",
  "846": "TV - Confirmar Alteração de Plano",
  "847": "Retrabalho de Confirmação - TV Alteração de Plano",
  "848": "TV - Faturar Alteração de Plano",
  "849": "TV - Pesquisar Qualidade Pós Alteração",
  "850": "Retrabalho de Solicitação - TV Alteração de Plano",
  "851": "Processo de Migração de Tecnologia",
  "852": "Solicitar Migração de Tecnologia",
  "853": "Confirmar Migração de Tecnologia",
  "854": "Migrar Tecnologia",
  "855": "Auditar Migração de Tecnologia",
  "856": "Retrabalho de Migração de Tecnologia",
  "857": "Faturar Migração de Tecnologia",
  "858": "Retrabalho de Auditoria - Migração de Tecnologia",
  "859": "Pesquisa Pós Migração de Tecnologia",
  "860": "Reter Cliente - Migração de Tecnologia",
  "861": "Cancelar Migração de Tecnologia",
  "862": "Cobrar Equipamentos - Migração de Tecnologia",
  "863": "Faturar Equipamentos - Migração de Tecnologia",
  "864": "Retirar Equipamentos - Migração de Tecnologia",
  "865": "Auditar Retirada - Migração de Tecnologia",
  "866": "Retrabalho de Retirada - Migração de Tecnologia",
  "867": "Retrabalho de Cobrança - Migração de Tecnologia",
  "868": "Comercial - Viabilidade em Análise",
  "869": "Processo de Contagem de Portas",
  "870": "Contar Portas",
  "871": "Analisar Contagem",
  "872": "Faturar Portas",
  "873": "Problema na Instalação",
  "874": "Enviar Retorno ao Cliente",
  "888": "Processo de Alteração de Plano",
  "889": "Solicitar Alteração de Plano",
  "890": "Confirmar Alteração de Plano",
  "891": "Faturar Alteração de Plano",
  "892": "Retrabalho de Solicitação - Alteração de Plano",
  "893": "Retrabalho de Confirmação - Alteração de Plano",
  "894": "Executar Alteração de Plano",
  "895": "Auditoria de Alteração de Plano",
  "896": "Retrabalho de Execução - Alteração de Plano",
  "897": "Pesquisa Pós Alteração de Plano",
  "898": "Reter Cliente - Alteração de Plano",
  "899": "Cancelar Alteração de Plano",
  "900": "Processo de Mudança de Endereço",
  "901": "Solicitar Mudança de Endereço",
  "902": "Confirmar Mudança de Endereço",
  "903": "Mudar de Endereço",
  "904": "Faturar Mudança de Endereço",
  "905": "Auditar Mudança de Endereço",
  "906": "Retrabalho de Mudança de Endereço",
  "907": "Pesquisa Pós Mudança de Endereço",
  "908": "Reter Cliente - Mudança de Endereço",
  "909": "Cancelar Mudança de Endereço",
  "910": "Retrabalho de Solicitação - Mudança de Endereço",
  "911": "Retrabalho de Confirmação - Mudança de Endereço",
  "912": "Cobrar Equipamentos - Mudança de Endereço",
  "913": "Faturar Equipamentos - Mudança de Endereço",
  "914": "Retirar Equipamentos - Mudança de Endereço",
  "915": "Auditar Retirada - Mudança de Endereço",
  "916": "Retrabalho de Retirada - Mudança de Endereço",
  "917": "Retrabalho de Cobrança - Mudança de Endereço",
  "918": "Coletar Assinatura - Mudança de Endereço",
  "919": "Processo de Alteração de Vencimento",
  "920": "Solicitar Alteração de Vencimento",
  "921": "Confirmar Alteração de Vencimento",
  "922": "Retrabalho de Solicitação - Alteração de Vencimento",
  "960": "Contar Estoque",
  "961": "Analisar Estoque (Falta)",
  "962": "Efetuar Cobrança",
  "963": "Analisar Estoque (Sobra)",
  "964": "Ajustar Falta",
  "965": "Corrigir Falta",
  "966": "Conferir Correção",
  "967": "Retrabalho de Correção",
  "968": "Ajustar Sobra",
  "969": "Corrigir Sobra",
  "970": "Processo de Contagem de Estoque",
  "971": "Analisar Estoque (Falta/Sobra)",
  "972": "Ajustar Falta/Sobra",
  "973": "Corrigir Falta/Sobra",
  "974": "Identificar Erro no Pagamento",
  "975": "Lançar Tarifa",
  "976": "Contatar Cliente",
  "977": "Corrigir Financeiro",
  "978": "Retrabalho de Solicitação - Erro no Retorno",
  "979": "Devolver Valor",
  "980": "Enviar Comprovante",
  "981": "Processo de Correção de Erro no Retorno",
  "983": "TV - Reverter Cancelamento",
  "984": "TV - Faturar Cancelamento",
  "985": "Retrabalho de Reversão - TV",
  "986": "Processo de Cancelamento de TV",
  "987": "Processo de Retrabalho",
  "988": "Identificar Divergência",
  "989": "Retrabalho Processual",
  "990": "Conferir Correção",
  "991": "TEL - Solicitar Troca de Atributo",
  "992": "Solicitar Consulta - SPC",
  "993": "Consultar SPC",
  "994": "Revisar Consulta - SPC",
  "995": "Retornar Consulta - SPC",
  "996": "Retrabalho de Consulta - SPC",
  "997": "Processo de Consulta no SPC",
  "998": "Processo - Grupo Central Soluções em Cobranças",
  "999": "GCS - Revisar Contrato",
  "1000": "GCS - Acompanhar",
  "1001": "GCS - Faturar Financeiro",
  "1002": "GCS - Enviar Planilha",
  "1004": "GCS - Receber Repasse",
  "1005": "Processo de Devolução da Central",
  "1006": "GCS - Solicitar Devolução",
  "1007": "Retrabalho de Confirmação - Cancelamento",
  "1008": "Coletar Assinatura - Alteração de Plano",
  "1009": "Coletar Assinatura - Mudança de Endereço",
  "1010": "Coletar Assinatura - Troca de Titularidade",
  "1011": "Coletar Assinatura - Contratação de SVA",
  "1012": "TV - Coletar Assinatura - Alteração de Plano",
  "1013": "TV - Coletar Assinatura - Ativação",
  "1014": "Coletar Assinatura - Cobrança",
  "1015": "Coletar Assinatura - Suspensão Temporária",
  "1016": "Coletar Assinatura - Cancelamento",
  "1017": "Coletar Assinatura - Débito Automático",
  "1018": "Coletar Assinatura - Migração de Tecnologia",
  "1019": "TEL - Coletar Assinatura - Alteração de Plano",
  "1020": "TEL - Coletar Assinatura (Número Novo)",
  "1021": "TEL - Coletar Assinatura (Portabilidade)",
  "1022": "TEL - Coletar Assinatura - Portabilidade/TT",
  "1023": "Receber Pagamento - Suspensão Temporária",
  "1024": "TEL - Coletar Assinatura - Troca de Titularidade",
  "1025": "Processo de Envio de Cobrança para Assessoria",
  "1026": "Enviar para Édimo",
  "1027": "Enviar para Métrica",
  "1028": "Enviar para Central",
  "1029": "Negociar Inadimplência - Assessoria",
  "1030": "Cancelar Financeiro - Assessoria",
  "1031": "Excluir SPC - Assessoria",
  "1032": "Desativar Contrato - Assessoria",
  "1033": "Preparar Envio",
  "1034": "Faturar Inadimplência - Cobrança",
  "1035": "Confirmar Renegociação - Cobrança",
  "1036": "Confirmar Assinatura - Cobrança",
  "1037": "Faturar Renegociação - Cobrança",
  "1038": "Processo de Reativação",
  "1039": "Solicitar Reativação",
  "1040": "Confirmar Reativação",
  "1041": "Reativar Internet",
  "1042": "Coletar Assinatura - Reativação",
  "1043": "Retrabalho de Solicitação - Reativação",
  "1044": "Auditar Reativação",
  "1045": "Faturar Reativação",
  "1046": "Retrabalho de Reativação",
  "1047": "Reter Cliente - Reativação",
  "1048": "Retrabalho de Confirmação - Reativação",
  "1049": "Retrabalho de Auditoria - Reativação",
  "1050": "Desistir Pré-Contrato - Reativação",
  "1052": "Processo de Cobrança",
  "1053": "Negociar Inadimplência - Renegociação",
  "1054": "Confirmar Negociação - Renegociação",
  "1055": "Faturar Inadimplência - Renegociação",
  "1056": "Renegociar Negociação - Renegociação",
  "1057": "Confirmar Renegociação - Renegociação",
  "1058": "Faturar Renegociação - Renegociação",
  "1059": "Confirmar Assinatura - Renegociação",
  "1060": "Processo de Renegociação",
  "1061": "Coletar Assinatura - Renegociação",
  "1062": "Cobrar Inadimplência - Renegociação",
  "1063": "Retrabalho de Cobrança - Renegociação",
  "1064": "Confirmar Ativação - Ativação Fibra/Rádio",
  "1065": "Processo de Verificação de Viabilidade",
  "1066": "Solicitar Verificação de Viabilidade",
  "1067": "Verificar Viabilidade",
  "1068": "Retorno de Viabilidade",
  "1069": "Retrabalho de Verificação",
  "1070": "Pesquisa Pós Cobrança",
  "1071": "Pesquisa de Reversão - Cancelamento",
  "1072": "Receber Pagamento - Renegociação",
  "1073": "Retrabalho de Recebimento - Renegociação",
  "1074": "Auditar Renegociação",
  "1075": "Processo de Suporte Fibra",
  "1076": "Triagem de Suporte - Fibra",
  "1077": "Suporte N2 - Fibra",
  "1078": "Suporte Externo - Fibra",
  "1079": "Auditoria Técnica - Fibra",
  "1080": "Retrabalho Técnico - Fibra",
  "1081": "Pesquisa Pós Suporte - Fibra",
  "1082": "Faturar Manutenção - Fibra",
  "1083": "Processo de Suporte Rádio",
  "1084": "Triagem de Suporte - Rádio",
  "1085": "Suporte N2 - Rádio",
  "1086": "Suporte Externo - Rádio",
  "1087": "Auditoria Técnica - Rádio",
  "1088": "Retrabalho Técnico - Rádio",
  "1089": "Pesquisa Pós Suporte - Rádio",
  "1090": "Faturar Manutenção - Rádio",
  "1091": "Desconto por Indicação",
  "1092": "Retrabalho de Negociação - Renegociação",
  "1093": "Auditar Negociação - Renegociação",
  "1226": "NÃO USAR - Processo Troca de Titularidade",
  "1227": "Solicitar Troca de Titularidade",
  "1228": "Faturar Troca de Titularidade",
  "1229": "Acompanhar Pagamento - Titularidade",
  "1230": "Retrabalho de Solicitação - Titularidade",
  "1231": "Confirmar Troca de Titularidade",
  "1232": "Cancelar Nota Fiscal - Titularidade",
  "1233": "Cancelar Financeiro - Titularidade"
};

/**
 * Retorna o nome da categoria pelo ID.
 * O mapa de categorias é exclusivo da D-Kiros.
 * Para outros ISPs, retorna o ID bruto (evita exibir nomes de outra empresa).
 */
export function getCategoriaName(id: string | number, ispId?: string): string {
  const idStr = String(id);
  // Só usar o mapa para D-Kiros (proprietária dos dados de categorias)
  if (!ispId || ispId === "d-kiros") {
    return categoriasMap[idStr] || idStr;
  }
  // Para outros ISPs, retornar apenas o ID numérico (sem nomes de outra empresa)
  return idStr;
}

/**
 * Retorna o nome amigável da categoria para exibição.
 * Usa categoriasMap somente para D-Kiros; outros ISPs mostram "Categoria {id}".
 */
export function getCategoriaDisplay(id: string | number, ispId?: string): string {
  const idStr = String(id);
  if (!ispId || ispId === "d-kiros") {
    return categoriasMap[idStr] || `Categoria ${idStr}`;
  }
  return `Categoria ${idStr}`;
}
