// Mapeamento de IDs de categorias para nomes de assuntos
// Gerado a partir de relatorio_assuntos.csv (apenas ativos)

export const categoriasMap: Record<string, string> = {
  "10": "Financeiro - Negociação de IP estático",
  "11": "Reclamação de Serviços",
  "13": "Interesse em Fibra Óptica",
  "15": "Processo de Desconto",
  "18": "Venda de Serviços Voip",
  "23": "Rede D-Kiros Internert - Manutenção de POP",
  "28": "Mudança de Tecnologia",
  "35": "Externo - Retirada de equipamento (cancelamento)",
  "38": "Comercial - Pós-venda (Instalação)",
  "39": "Emitir Contrato de Upgrade",
  "51": "Financeiro - Comprovante de Pagamento",
  "54": "Financeiro - Acompanhar pagamento",
  "55": "Financeiro - Boleto atualizado",
  "56": "Financeiro - Cheque",
  "57": "Financeiro - Emissão de boletos",
  "58": "Incluir no SPC",
  "59": "Emitir Contrato de Vendas",
  "60": "Retorno de Negociação",
  "61": "Ligacao para Lembrete / Cobranca / Aviso",
  "62": "Cobrança - Negociação Bemtevi 2015",
  "63": "Cobrança - Negociação de inadimplência",
  "64": "Cobrança - Negociação GCP",
  "65": "Nota Fiscal",
  "66": "Financeiro - Pagamento duplicado",
  "67": "Financeiro - Negociação de ponto de repetição",
  "68": "Reverter Cancelamento",
  "69": "Automatizada",
  "72": "Rede D-Kiros - instalação de equipamento em POP's",
  "73": "Retirada de equipamentos (Migração)",
  "77": "Comercial - Ligar/Retornar",
  "78": "Assuntos Internos - Colaboradores",
  "81": "Verificar Viabilidade",
  "82": "Financeiro - Emissão de contratos (TORRE)",
  "85": "Comercial - IP Fixo (estático)",
  "86": "Externo - Manutenção no cabeamento",
  "87": "Mudança de endereço - Instalação",
  "88": "Mudança de endereço - Retirada",
  "89": "Financeiro - Mudança de titularidade",
  "90": "Financeiro - Mudança de vencimento",
  "94": "Externo - Troca de cômodo",
  "100": "Instalação Fibra Óptica",
  "102": "Definir setor de viabilidade",
  "103": "Sem internet por falta de pagamento",
  "104": "Comercial - Agendamento Instalação",
  "106": "Bloquear Contrato",
  "107": "Financeiro - Outros/SPC",
  "108": "Financeiro - Emissão de boletos pós manutenção",
  "109": "SAC - Solicitação de cancelamento",
  "110": "Confirmação de cancelamento",
  "111": "Financeiro - Dúvidas financeiras",
  "112": "Financeiro - Solicitação de débito automático",
  "113": "Financeiro - Confirmação de débito automático",
  "114": "Comercial - Elogio do cliente",
  "116": "Financeiro - Central do Assinante",
  "117": "Atendimento - Atualização de cadastro",
  "118": "Financeiro - Permuta de serviços",
  "119": "Correção indicada pelo cliente",
  "120": "Retrabalho Chamado Técnico NPS",
  "121": "Financeiro - Venda de cabo de rede",
  "123": "Excluir no SPC",
  "126": "Cancelamento de IP Fixo",
  "127": "Degustação (upgrade e downgrade)",
  "128": "Chamado Técnico NPS",
  "129": "CRT - Pós Pesquisa Manutenção/Falha",
  "130": "Financeiro em Atraso",
  "131": "CAT - NPS",
  "134": "INFRA - Falha rede D-kiros",
  "135": "CRT - Pós Pesquisa Sem conexão",
  "137": "CRT - Pós Pesquisa Lentidão",
  "138": "CRT - Pesquisa NPS",
  "139": "CRT - Pós Pesquisa Quedas",
  "140": "Incluir IP Fixo",
  "141": "CRT - Pós Pesquisa Assistência",
  "142": "CRT - Pós Pesquisa Telefonia VOIP",
  "143": "Aditivo de Contrato",
  "145": "Financeiro - Pagseguro",
  "146": "CAT - Pesquisa NPS",
  "147": "Externo - Troca de equipamento para melhoria de sinal",
  "148": "Externo - Troca de antena para torre nova",
  "149": "CRT - Pós Pesquisa Preventivo",
  "151": "Liberação de acesso",
  "156": "INATIVO --- Cobrança - Ligação cobrança",
  "157": "CRT - Pesquisa de atendimento",
  "162": "Externo - Retirada de equipamentos de POP",
  "163": "Mudança de titularidade",
  "164": "Externo - Reinstalação de equipamentos",
  "166": "Entrega de carnê",
  "168": "INATIVO --- Externo - Cobrança externa",
  "169": "Assuntos Financeiros",
  "171": "Financeiro - Pagamento não encontrado",
  "173": "Pagamento Cancelado",
  "175": "Externo - troca de equipamentos para padronização do pop",
  "176": "SAC - Pesquisa de Satisfação",
  "177": "Comercial - Sem viabilidade do sinal",
  "178": "PÓS PESQUISA N2 - CRT",
  "179": "PÓS PESQUISA UPCALL - CRT",
  "180": "Inconsistência Cadastral",
  "181": "Atendimento Belluno",
  "182": "Adesão ao Contrato 2017",
  "183": "Atendimento Inicial",
  "184": "Financeiro - Débito Automático (Inconsistência)",
  "185": "Financeiro - Alteração de forma de recebimento de faturas",
  "186": "INATIVO -- Cobrança - Cancelamento/Inadimplência",
  "187": "Mudança de Plano - Upgrade",
  "188": "Mudança de Plano - Downgrade",
  "189": "Agendamento de horário",
  "190": "Rede D-Kiros - Projeto novo",
  "191": "Comercial - Levantamento de Demanda de Cliente",
  "192": "Estoque - Levantamento de Equipamentos",
  "193": "MANUTENÇÃO/FALHA - CRT",
  "194": "Financeiro - Avaliar Viabilidade Financeira do Projeto",
  "195": "Comercial - Libera Comercial para Vendas",
  "196": "Financeiro - Envio de boleto",
  "197": "Comercial - Pós venda",
  "198": "RETRABALHO MANUTENÇÃO/FALHA - CRT",
  "199": "Envio de Formulario de Portabilidade Voip",
  "200": "Comercial - Solicitar assinatura nos Termos",
  "201": "PESQUISA PÓS ATENDIMENTO MANUTENÇÃO/FALHA",
  "202": "Externo - Visita de viabilidade",
  "203": "Comercial - Viabilidade negada",
  "204": "Comercial - Cadastro Prospecção",
  "205": "Comercial - Consulta no SPC",
  "206": "Comercial - Retornar para fechar venda",
  "207": "Comercial - Completa Cadastro do Cliente",
  "208": "Estoque - Separar Equipamentos da instalação",
  "210": "Vender Produtos",
  "211": "Chamado técnico",
  "213": "Desenvolvimento e Parametrização",
  "215": "CANCELAMENTO",
  "216": "Cobrança (valores em aberto/produtos)",
  "219": "Faturar venda de produtos",
  "221": "Retorno de Viabilidade",
  "222": "REGISTRO DE ATENDIMENTO GERAL",
  "223": "INATIVO --- Mudança de endereço",
  "224": "INATIVO - TROCA DE PLANO",
  "225": "INATIVO - TROCA DE TITULARIDADE",
  "226": "INATIVO --- TROCA DE VENCIMENTO",
  "227": "INATVO - Venda Residencial",
  "228": "EMPRESARIAL- VENDA",
  "232": "Reclamação Comercial",
  "233": "Externo - Manutenção",
  "234": "Recadastramento de cliente",
  "235": "Instalação de conexão temporária",
  "236": "Comercial - Pré-venda",
  "237": "Externo - Manut. preventiva na rede",
  "238": "Instalação Rádio",
  "239": "Confirmação de venda",
  "240": "Auditoria de Instalação",
  "241": "Processo de Ativação",
  "242": "Consultar SPC",
  "243": "TESTE CRT",
  "244": "CRT - Liberação de contrato",
  "245": "Reativar Contrato",
  "246": "Solicitação Degustação",
  "247": "Externo - Verificação",
  "248": "Financeiro - Não Descontar Débito Automático",
  "249": "Retornar Contato",
  "250": "Atendimento Ativo",
  "251": "Auditoria de Manutenção",
  "252": "Retrabalho de Manutenção",
  "253": "Emitir Contrato de Mudança de Endereço",
  "254": "Financeiro - Contestação de débito",
  "255": "Financeiro - Contestar desconto",
  "256": "Financeiro - Parcelamento de atraso",
  "259": "Troca de PPPoE",
  "260": "Comercial - Taxa de instalação",
  "261": "Cancelar Troca de endereço",
  "263": "CRT - Pós Pesquisa Instalação",
  "264": "Vender telefonia",
  "267": "CRT - Pós Pesquisa Vendas",
  "271": "Instalação de Ponto Adicional",
  "272": "Instalação CFTV",
  "273": "CRT - Pós Pesquisa Comercial",
  "274": "Cobrança - IPVA",
  "275": "CRT - Pós Pesquisa Migração",
  "276": "Cobrança - Manutenção (Entrega de Carnê/Cobrança)",
  "277": "Cobrança - Tráfego Telefônico",
  "278": "Cobrança - Instalação Tardia (Primeira Fatura)",
  "279": "Processo de Cobrança - Aviso de Corte",
  "280": "CRT - Pós Pesquisa Retirada de Equip",
  "281": "CRT - Pós Pesquisa Retirada Equip (Cancelamento)",
  "282": "CRT - Pós Pesquisa Troca de Comodo",
  "283": "CRT - Pós Pesquisa Mudança de Endereço",
  "284": "Externo - Reinstalação após cancelamento",
  "285": "Cobrança - Instalação",
  "286": "CRT - Pós Pesquisa Ponto Adicional",
  "287": "Cobrança - Evento programado",
  "288": "Financeiro - Dispensa de juros",
  "289": "Financeiro - Parcelamento de produto",
  "290": "Comercial - Taxa de mudança",
  "291": "Retorno (Financeiro bloqueado)",
  "292": "Cobrança - Visita externa",
  "293": "Financeiro - Descontar Débito Automático",
  "294": "Financeiro - Contestar Cobrança",
  "295": "Externo - Reinstalação após Inadimplência",
  "296": "Análise de Sinal",
  "297": "Financeiro - Emissão nota fiscal",
  "298": "CRT - ATENDIMENTO",
  "299": "CRT - Pós Pesquisa Atendimento",
  "300": "CRT - Suporte Externo",
  "301": "Retrabalho SUPORTE EXTERNO - CRT",
  "302": "Teste Externo",
  "303": "Monitorar CTO Lotada",
  "304": "Monitorar Caixa de Emenda Afetada",
  "305": "Externo - Fila Única",
  "308": "Passagem de cabo",
  "309": "Problema de Instalação",
  "310": "NEGOCIAR- CRT",
  "312": "CAT - Pesquisa de atendimento",
  "313": "Pesquisa - Pós venda - AUTOMATIZADA",
  "314": "Pesquisa - Pós vendas (novo)",
  "315": "CRT - Retrabalho Atendimento",
  "316": "RETRABALHO N2 UPCALL - CRT",
  "317": "Auditoria da Pesquisa de Pós Venda",
  "318": "Instalação de ponto adicional CFTV",
  "319": "Mudança de endereço CFTV",
  "320": "Manutenção CFTV",
  "321": "Processo de Retenção",
  "322": "Reter Cliente",
  "323": "Pesquisa Pós Retenção",
  "324": "Retrabalho de Retenção",
  "325": "Auditoria de Retenção",
  "326": "Cancelamento por Insatisfação",
  "327": "Comercial - Vendedor Externo",
  "328": "Desistir de Pré-contrato",
  "329": "Comercial - Viabilidade em Análise",
  "330": "Processo de Cancelamento - Inabilitar contrato",
  "331": "Confirmar Cancelamento - GCA",
  "332": "Retirar Equipamentos - Cancelamento",
  "333": "Auditar Cancelamento",
  "334": "Faturar Cancelamento",
  "335": "Retrabalho Técnico - Cancelamento",
  "336": "Pesquisa de Cancelamento",
  "337": "Cancelar Contrato - Não Localizado",
  "338": "Cobrar Equipamentos - Cancelamento",
  "339": "Faturar Equipamentos - Cancelamento",
  "340": "Negativar Contrato - Equipamento",
  "341": "Auditoria de Instalação",
  "342": "Retrabalho de Instalação",
  "343": "Faturar Instalação",
  "344": "Pesquisa Pós Instalação",
  "345": "Confirmar Viabilidade",
  "346": "Confirmar Instalação",
  "347": "Emitir Contrato - Instalação",
  "348": "Coletar Assinatura - Instalação",
  "349": "Instalar Cliente",
  "350": "Renegociar Instalação",
  "351": "Retrabalho de Confirmação - Instalação",
  "352": "Revisão de Materiais",
  "353": "Corrigir Bloqueio de Contrato",
  "354": "Retrabalho de Assinatura",
  "355": "Emitir Carta Corte - BO",
  "356": "Cobrança - Emitir Carta Corte",
  "357": "Processo de Cancelamento",
  "358": "Solicitar Cancelamento",
  "359": "Processo de Ativação Fibra/Rádio",
  "360": "Solicitar Ativação - Fibra/Rádio",
  "361": "Confirmar Ativação",
  "362": "Coletar Assinatura",
  "363": "Confirmar Assinatura",
  "364": "Instalar Cliente - Fibra/Rádio",
  "365": "Auditar Instalação - Fibra/Rádio",
  "366": "Faturar Ativação",
  "367": "Pesquisar Qualidade",
  "368": "Retrabalho de Instalação - Fibra/Rádio",
  "369": "Reter Cliente - Fibra/Rádio",
  "370": "Retrabalho de Solicitação",
  "371": "Retrabalho de Confirmação",
  "372": "Confirmar Viabilidade Técnica",
  "373": "Problema na Instalação",
  "374": "Processo de Mudança de Endereço",
  "375": "Solicitar Mudança de Endereço",
  "376": "Confirmar Mudança de Endereço",
  "377": "Coletar Assinatura - Mudança de Endereço",
  "378": "Confirmar Assinatura - Mudança de Endereço",
  "379": "Retrabalho de Solicitação - Mudança de Endereço",
  "380": "Retirada de Equipamentos - Mudança de Endereço",
  "381": "Auditoria Técnica - Mudança de Endereço",
  "382": "Reter Cliente - Mudança de Endereço",
  "383": "Falha na Retirada - Mudança de Endereço",
  "384": "Retrabalho de Confirmação - Mudança de Endereço",
  "385": "Retrabalho de Assinatura - Mudança de Endereço",
  "386": "Faturar Mudança de Endereço",
  "387": "Nova Tentativa de Retirada - Mudança de Endereço",
  "388": "Nova Tentativa de Mudança",
  "389": "Retrabalho de Mudança de Endereço",
  "390": "Pesquisar Qualidade - Mudança de Endereço",
  "391": "Cobrar Equipamentos - Mudança de Endereço",
  "392": "Auditoria de Comodato - Mudança de Endereço",
  "393": "Faturar Equipamentos - Mudança de Endereço",
  "394": "Negativar Contrato - Mudança de Endereço",
  "395": "Falha na Mudança de Endereço",
  "396": "Retrabalho Técnico - Mudança de Endereço",
  "397": "Devolver Comodato - Mudança de Endereço",
  "398": "Viabilidade Negada",
  "399": "Pesquisa - Pós Ativação",
  "400": "Auditoria de Pesquisa",
  "401": "Retorno de Pesquisa",
  "402": "Retrabalho de Pesquisa",
  "403": "Pesquisa CSAT",
  "404": "Pesquisa Ativação Cliente",
  "405": "Pesquisa Manutenção",
  "406": "Pesquisa Retrabalho",
  "407": "Pesquisa Mudança de Endereço",
  "408": "Pesquisa Cancelamento",
  "409": "Auditoria Pesquisa CSAT",
  "410": "Retorno CSAT",
  "411": "Retrabalho Pesquisa CSAT",
  "412": "Auditoria de Instalação - Mudança de Endereço",
  "413": "Processo de Liberação de Acesso",
  "414": "Solicitar Liberação de Acesso",
  "415": "Liberar Acesso",
  "416": "Retrabalho de Liberação",
  "417": "Cobrança - Trafego não medido",
  "418": "Retrabalho de Instalação - Fibra",
  "419": "Mudança de Endereço Fibra",
  "420": "Processo de Renegociação",
  "421": "Negociar Renegociação",
  "422": "Faturar Renegociação",
  "423": "Acompanhar Pagamento",
  "424": "Retrabalho de Negociação",
  "425": "Excluir no SPC - Renegociação",
  "426": "Cancelar Renegociação",
  "427": "Cobrar Acordo",
  "428": "Desativar Contrato",
  "429": "Enviar para Assessoria",
  "430": "Reativar Contrato - Renegociação",
  "431": "Auditoria de Negociação",
  "432": "Incluir no SPC - Renegociação",
  "433": "Retrabalho de Auditoria - Renegociação",
  "434": "Reverter Negativação",
  "435": "Pesquisa de Renegociação",
  "436": "Processo de Migração de Tecnologia",
  "437": "Solicitar Migração",
  "438": "Confirmar Migração",
  "439": "Coletar Assinatura - Migração",
  "440": "Confirmar Assinatura - Migração",
  "441": "Retrabalho de Solicitação - Migração",
  "442": "Migrar Cliente",
  "443": "Auditoria de Migração",
  "444": "Reter Cliente - Migração",
  "445": "Retrabalho Técnico - Migração",
  "446": "Faturar Migração",
  "447": "Retirar Equipamentos - Migração",
  "448": "Auditoria de Retirada - Migração",
  "449": "Retrabalho de Retirada - Migração",
  "450": "Cobrar Equipamentos - Migração",
  "451": "Faturar Equipamentos - Migração",
  "452": "Negativar Contrato - Migração",
  "453": "Pesquisa Pós Migração",
  "454": "Confirmar Viabilidade - Migração",
  "455": "Problema na Migração",
  "456": "Falha na Migração",
  "457": "Retrabalho de Confirmação - Migração",
  "458": "CRT - Pesquisa de Instalação",
  "459": "CRT - Inclusão Temporária",
  "460": "CRT - Inclusão degustação",
  "461": "Fibra - Auditoria da Solicitação",
  "462": "Fibra - Mudança de Endereço",
  "463": "Fibra - Auditoria da Mudança de End.",
  "464": "Fibra - Falha na Mudança de Endereço",
  "465": "Fibra - Faturamento de Mudança de Endereço",
  "466": "Fibra - Nova Tentativa de Mudança",
  "467": "Fibra - Retrabalho Técnico",
  "468": "Remoção do Conector",
  "469": "Retirada de Equipamento(s)",
  "470": "Auditoria de Retirada do(s) Equip.",
  "471": "Cobrar Equipamentos - Mudança",
  "472": "Faturar Equipamentos - Mudança",
  "473": "Cancelamento De Pré-Cadastro",
  "474": "Viável apenas em Rádio",
  "475": "Fibra - Retrabalho de Auditoria",
  "476": "Retrabalho de Retirada de Equipamentos",
  "477": "Revisar financeiro",
  "478": "Negativar Contrato - SPC",
  "479": "Retrabalho Técnico de Mudança de Endereço",
  "480": "Auditoria Pós Devolução de Comodato",
  "481": "CRT - Liberação de contrato",
  "482": "Chamado técnico - Preventivo",
  "483": "Confirmação de cancelamento IP Fixo",
  "484": "Análise de Viabilidade de Velocidade",
  "485": "Alteração de Plano",
  "486": "Cancelamento da Solicitação",
  "487": "Faturamento da Alteração de Plano",
  "488": "Auditar Mudança de Endereço e Tecnologia",
  "489": "Solicitação de Cancelamento",
  "490": "Retirada da Antena",
  "491": "Auditoria Pós Retirada da Antena",
  "492": "Executar Processo",
  "493": "Retrabalho de Auditoria - Migração",
  "494": "Solicitar Telefonia",
  "495": "TEL - Confirmar Ativação (Portabilidade)",
  "496": "TEL - Confirmar Ativação (Número Novo)",
  "497": "TEL - Configurar Linha SIP",
  "498": "Instalação de Telefonia",
  "499": "Auditar Instalação de Telefonia",
  "500": "TEL - Faturar Ativação",
  "501": "Retrabalho Técnico - Telefonia",
  "502": "Pesquisa Pós Instalação de Telefonia",
  "503": "Retrabalho de Contrato - Telefonia",
  "505": "Retrabalho da Solicitação de Telefonia",
  "506": "Retrabalho da Solicitação de Telefonia - Vendas",
  "507": "Processo de Troca de Titularidade",
  "508": "Confirmar Troca de Titularidade",
  "509": "Retrabalho de Solicitação - Titularidade",
  "510": "Cancelar Troca de Titularidade",
  "511": "Desistir Pré-Contrato - Titularidade",
  "512": "Atualizar PPPOE Remotamente",
  "513": "Auditoria Técnica - Titularidade",
  "514": "Falha na Visita Técnica - Titularidade",
  "515": "Nova Tentativa de Visita Técnica",
  "516": "Solicitação de Cancelamento - Titularidade",
  "517": "Retrabalho Tecnico - Titularidade",
  "518": "Faturar Troca de Titularidade",
  "519": "Solicitar Troca de Titularidade",
  "520": "Autorização de Troca de Titularidade",
  "521": "Retrabalho de Solicitação - Titularidade",
  "522": "Faturar Novo Titular",
  "523": "Pesquisa Pós Ativação Novo Titular",
  "524": "Inativar Antigo Titular",
  "525": "Visita Técnica - Titularidade",
  "526": "Processo de Bloqueio Temporário",
  "527": "Solicitar Suspensão",
  "528": "Retrabalho de Solicitação - Suspensão",
  "529": "Retrabalho de Confirmação - Suspensão",
  "530": "Faturar Suspensão",
  "531": "Confirmar Suspensão",
  "532": "Processo de Alteração de Recebimento",
  "533": "Solicitar Alteração de Recebimento",
  "534": "Retrabalho de Solicitação - Recebimento",
  "535": "Confirmar Alteração de Recebimento",
  "536": "Retrabalho de Confirmação - Recebimento",
  "537": "Aguardar Fechamento do Mês",
  "538": "Alteração de Vencimento",
  "539": "Gerar Cobrança - Recebimento",
  "540": "Processo de Alteração de Vencimento",
  "541": "Solicitar Alteração de Vencimento",
  "542": "Retrabalho de Solicitação - Vencimento",
  "543": "Confirmar Alteração de Vencimento",
  "544": "Retrabalho de Confirmação - Vencimento",
  "545": "Faturar Alteração de Vencimento",
  "546": "Processo de Nota Fiscal",
  "547": "Solicitar Nota Fiscal",
  "548": "Retrabalho de Solicitação - NF",
  "549": "Emitir Nota Fiscal",
  "550": "Retrabalho de Emissão - NF",
  "551": "Entregar Nota Fiscal",
  "552": "Auditoria Nota Fiscal",
  "553": "Retrabalho de Auditoria - NF",
  "554": "Processo Diversos",
  "555": "Solicitar Atendimento",
  "556": "Executar Solicitação",
  "557": "Enviar Retorno ao Cliente",
  "558": "Atendimento Geral",
  "559": "Retrabalho de Solicitação - Diversos",
  "560": "Envio para Assessoria",
  "561": "Auditar Envio para Assessoria",
  "562": "Retrabalho de Cobrança",
  "563": "Retrabalho de Assessoria",
  "564": "Incluir no SPC - Assessoria",
  "565": "Envio de Cobrança para Assessoria",
  "566": "Enviar para Métrica",
  "567": "Enviar para Édimo",
  "568": "Auditar Novos Envios",
  "569": "Auditar Devoluções",
  "570": "Acompanhar Devoluções",
  "571": "Inativar Contrato - Assessoria",
  "572": "Cobrança Pré Assessoria",
  "573": "Inclusão SPC Externo",
  "574": "Enviar para Não Localizado",
  "575": "Cobrança de Equipamentos",
  "576": "Processo de Cancelamento de Telefonia",
  "577": "Solicitar Cancelamento de Telefonia",
  "578": "Confirmar Cancelamento - Telefonia",
  "579": "Faturar Cancelamento - Telefonia",
  "580": "Reter Cliente - Telefonia",
  "581": "Pesquisar Qualidade - Telefonia",
  "582": "Retrabalho de Solicitação - Telefonia",
  "583": "Retrabalho de Confirmação - Telefonia",
  "584": "TEL - Confirmação de Cancelamento",
  "585": "Agendar Instalação",
  "586": "Reagendar Instalação",
  "587": "Pesquisar Instalação",
  "588": "Agendar Manutenção",
  "589": "Reagendar Manutenção",
  "590": "Pesquisar Manutenção",
  "591": "Confirmar Cancelamento",
  "592": "Agendar Cancelamento",
  "593": "Reagendar Cancelamento",
  "594": "Agendar Mudança de Endereço",
  "595": "Reagendar Mudança de Endereço",
  "596": "Agendar Migração",
  "597": "Reagendar Migração",
  "598": "Pesquisar Migração",
  "599": "Pesquisar Mudança de Endereço",
  "600": "Pesquisar Cancelamento",
  "606": "Solicitar Contratação de SVA",
  "607": "Confirmar Contratação de SVA",
  "608": "Coletar Assinatura - SVA",
  "609": "Ativar Cliente - SVA",
  "610": "Auditar Ativação - SVA",
  "611": "Faturar Ativação - SVA",
  "612": "Pesquisar Qualidade - SVA",
  "613": "Retrabalho Técnico - SVA",
  "614": "Reter Cliente - SVA",
  "615": "Retrabalho de Solicitação - SVA",
  "616": "Retrabalho de Confirmação - SVA",
  "617": "Problema na Ativação - SVA",
  "618": "Processo de Contratação de SVA",
  "619": "Solicitar Cancelamento de SVA",
  "620": "Confirmar Cancelamento - SVA",
  "621": "Retirar Equipamentos - SVA",
  "622": "Auditar Retirada - SVA",
  "623": "Faturar Cancelamento - SVA",
  "624": "Reter Cliente - Cancelamento SVA",
  "625": "Pesquisar Qualidade - Cancelamento SVA",
  "626": "Retrabalho de Solicitação - Cancelamento SVA",
  "627": "Retrabalho de Confirmação - Cancelamento SVA",
  "628": "Retrabalho de Retirada - SVA",
  "629": "Cobrar Equipamentos - SVA",
  "630": "Faturar Equipamentos - SVA",
  "631": "Negativar Contrato - SVA",
  "632": "Processo de Cancelamento de SVA",
  "633": "Auditoria de Instalação - SVA",
  "634": "Retrabalho de Instalação - SVA",
  "635": "Faturar Instalação - SVA",
  "636": "Faturar Materiais",
  "637": "Cobrar Materiais",
  "638": "Faturar Materiais - Cobrar",
  "639": "Negativar Contrato - Materiais",
  "640": "Retrabalho de Instalação",
  "641": "Reter Cliente - Cancelamento",
  "642": "Solicitar Instalação",
  "643": "Problemas com Áudio/Vídeo",
  "644": "Solicitar Alteração de Plano",
  "645": "Confirmar Alteração de Plano",
  "646": "Coletar Assinatura - Alteração de Plano",
  "647": "Ativar Cliente - Alteração de Plano",
  "648": "Faturar Alteração de Plano",
  "649": "Auditar Alteração de Plano",
  "650": "Pesquisar Qualidade - Alteração de Plano",
  "651": "Retrabalho de Solicitação - Alteração de Plano",
  "652": "Retrabalho de Confirmação - Alteração de Plano",
  "653": "Problema na Alteração de Plano",
  "654": "Retrabalho Técnico - Alteração de Plano",
  "655": "Reter Cliente - Alteração de Plano",
  "656": "Processo de Alteração de Plano",
  "657": "Confirmar Assinatura - Alteração de Plano",
  "658": "Solicitar Mudança de Endereço - SVA",
  "659": "Confirmar Mudança de Endereço - SVA",
  "660": "Coletar Assinatura - Mudança SVA",
  "661": "Confirmar Assinatura - Mudança SVA",
  "662": "Retrabalho de Solicitação - Mudança SVA",
  "663": "Retirar Equipamentos - Mudança SVA",
  "664": "Auditoria de Retirada - Mudança SVA",
  "665": "Reter Cliente - Mudança SVA",
  "666": "Falha na Retirada - Mudança SVA",
  "667": "Retrabalho de Confirmação - Mudança SVA",
  "668": "Nova Tentativa de Retirada - Mudança SVA",
  "669": "Mudar Endereço - SVA",
  "670": "Auditoria de Mudança - SVA",
  "671": "Nova Tentativa de Mudança - SVA",
  "672": "Faturar Mudança de Endereço - SVA",
  "673": "Pesquisar Qualidade - Mudança SVA",
  "674": "Cobrar Equipamentos - Mudança SVA",
  "675": "Auditoria de Comodato - Mudança SVA",
  "676": "Faturar Equipamentos - Mudança SVA",
  "677": "Negativar Contrato - Mudança SVA",
  "678": "Processo de Mudança de Endereço de SVA",
  "679": "Retrabalho Técnico - Mudança SVA",
  "680": "Retrabalho de Assinatura - Mudança SVA",
  "681": "Retrabalho de Retirada - Mudança SVA",
  "682": "Devolver Comodato - Mudança SVA",
  "683": "Falha na Mudança de Endereço - SVA",
  "684": "Problema na Mudança de Endereço - SVA",
  "685": "Cancelar Pré-Cadastro - Mudança SVA",
  "686": "Reter Cliente - Atendimento",
  "687": "CRT - Fazer atendimento CRT",
  "710": "Retorno da Viabilidade Técnica",
  "711": "Liberação Técnica",
  "712": "Pesquisa de Positivação",
  "713": "Retorno da Pesquisa de Positivação",
  "714": "Pesquisa de Reativação",
  "715": "Retorno de Pesquisa de Reativação",
  "716": "Retorno pós pesquisa com chamado",
  "717": "Retrabalho de Reativação",
  "718": "Retrabalho de Positivação",
  "719": "Pesquisa Pós Ativação de Venda - Novo",
  "720": "Pesquisa Pós Ativação de Venda - Retorno",
  "721": "Processo de Positivação",
  "722": "Pesquisa de Base",
  "723": "Retorno da Pesquisa de Base",
  "724": "Retorno Pós Pesquisa Base",
  "725": "Retrabalho Pós Pesquisa de Base",
  "726": "Processo de Pesquisa de Base",
  "727": "Pesquisa de Ativação",
  "728": "Retorno da Pesquisa de Ativação",
  "729": "Retorno Pós Pesquisa Ativação",
  "730": "Retrabalho Pós Pesquisa de Ativação",
  "731": "Processo de Pesquisa de Ativação",
  "732": "Pesquisa de Manutenção",
  "733": "Retorno da Pesquisa de Manutenção",
  "734": "Retorno Pós Pesquisa Manutenção",
  "735": "Retrabalho Pós Pesquisa de Manutenção",
  "736": "Processo de Pesquisa de Manutenção",
  "737": "Processo de Portabilidade/TT",
  "738": "Solicitar Portabilidade com TT",
  "739": "Retrabalho de Solicitação - Portabilidade",
  "740": "TEL - Confirmar Assinatura - Portabilidade",
  "741": "TEL - Solicitar Portabilidade",
  "742": "Portabilidade Reprovada",
  "743": "TEL - Solicitar Troca de Atributo",
  "744": "Agendar Instalação de TEL",
  "745": "Instalar Telefonia - Portabilidade",
  "746": "TEL - Auditoria de Instalação",
  "747": "Retrabalho de Instalação - Portabilidade",
  "748": "Faturar Ativação - Portabilidade",
  "749": "Pesquisa de Portabilidade",
  "750": "TEL - Cadastrar Linha SIP - Portabilidade",
  "751": "TEL - Configurar Central SIP",
  "752": "Retrabalho Técnico - Portabilidade",
  "753": "Reter Cliente - Portabilidade",
  "754": "TEL - Ativar Linha na Central",
  "755": "Retrabalho de Confirmação - Portabilidade",
  "756": "Auditar Portabilidade",
  "757": "Retrabalho de Contrato - Portabilidade",
  "758": "Coletar Assinatura - Portabilidade",
  "759": "Confirmar Assinatura - Portabilidade",
  "760": "TEL - Cancelar Linha SIP",
  "761": "TEL - Faturar Portabilidade",
  "762": "Retrabalho de Confirmação - Portabilidade/TT",
  "763": "Solicitar Troca de Titularidade - Portabilidade",
  "764": "TEL - Auditoria de Instalação - Portabilidade",
  "765": "Retrabalho de Instalação - Portabilidade/TT",
  "767": "MET - Receber Repasse",
  "768": "CRT - Manutenção/Falha",
  "769": "Chamado técnico - Manutenção/Falha",
  "770": "Retrabalho Chamado técnico - Manutenção/Falha",
  "771": "CRT - Retrabalho Manutenção/Falha",
  "772": "Auditoria de Infraestrutura",
  "773": "Negociação de Empreitada",
  "774": "Auditoria de Empreitada",
  "775": "Retrabalho de Empreitada",
  "776": "Passagem de Cabo",
  "777": "Auditoria de Passagem de Cabo",
  "778": "Retrabalho de Passagem de Cabo",
  "779": "Reverter Empreitada",
  "780": "Acompanhar Empreitada",
  "781": "Faturamento de Empreitada",
  "782": "Retrabalho de Contrato",
  "783": "Processo de Cancelamento por Inadimplência",
  "784": "Processo de Cancelamento de Telefonia por Inadimplência",
  "785": "Auditar Cancelamento - Inadimplência",
  "786": "Retrabalho de Faturamento - Inadimplência",
  "787": "Incluir no SPC - Inadimplência",
  "788": "Negativar Contrato - Inadimplência",
  "789": "Processo de Comprovante de Pagamento",
  "790": "Comprovante de Pagamento",
  "791": "Receber Pagamento",
  "792": "Retrabalho de Comprovante",
  "793": "Devolver Troca de Titularidade",
  "794": "Enviar Comprovante de Devolução",
  "795": "CS - Pesquisa pós atendimento CRT",
  "796": "CS - Pesquisa pós atendimento Upcall",
  "797": "Ativação de CTO / Ampliação de Portas",
  "798": "Renegociar Parcelamento",
  "799": "Manutenção de Infraestrutura",
  "800": "Acompanhar Suspensão",
  "801": "Remover Suspensão",
  "802": "Remover Suspensão Antecipadamente",
  "803": "Entregar Carnê - Suspensão",
  "804": "Auditoria de Transferencia Upcall",
  "805": "Agendar visita tecnica - CRT",
  "806": "Boletim de Ocorrência - B.O.",
  "807": "CRT - Comercial",
  "808": "Processo Judicial",
  "809": "Faturar Taxa de Ativação",
  "810": "Coletar Assinatura - Vendas",
  "811": "Retrabalho de Auditoria - Ativação",
  "812": "Receber Pagamento - Ativação",
  "813": "Inviabilidade de Degustação",
  "814": "CRT - Link TV",
  "815": "CRT - TV Assistência",
  "816": "CRT - Retrabalho TV Assistência",
  "817": "CRT - Pós Pesquisa TV Assistência",
  "818": "Processo de Ativação (Televisão)",
  "819": "TV - Solicitar Ativação",
  "820": "TV - Confirmar Ativação",
  "821": "TV - Faturar Ativação",
  "822": "TV - Visita Técnica",
  "823": "TV - Cobrar Assinatura",
  "824": "Retrabalho de Solicitação - TV",
  "825": "TV - Auditar Visita",
  "826": "Retrabalho Técnico - TV",
  "827": "Retrabalho de Auditoria - TV",
  "828": "Retrabalho de Confirmação - TV",
  "829": "TV - Pesquisar Qualidade",
  "830": "Receber Pagamento de Portas",
  "831": "Processo de Contagem de Portas",
  "832": "Processo de Alteração de Plano (Televisão)",
  "833": "TV - Solicitar Alteração de Plano",
  "834": "TV - Confirmar Alteração de Plano",
  "835": "TV - Faturar Alteração de Plano",
  "836": "TV - Cobrar Assinatura - Alteração",
  "837": "Retrabalho de Solicitação - TV Alteração",
  "838": "TV - Pesquisar Satisfação",
  "839": "Retrabalho de Confirmação - TV Alteração",
  "840": "TV - Visita Técnica - Alteração",
  "841": "TV - Auditar Visita - Alteração",
  "842": "Retrabalho de Visita - TV Alteração",
  "843": "TV - Publicar Contrato",
  "844": "Retrabalho de Auditoria - TV Alteração",
  "845": "Manutenção de Infraestrutura - Preventivo",
  "846": "Auditoria de Manutenção Preventiva",
  // IDs 847-1063 adicionados
  "847": "Retrabalho de Preventivo",
  "848": "Manutenção Preventiva - Cliente",
  "849": "Auditoria de Manutenção Preventiva - Cliente",
  "850": "Retrabalho de Manutenção Preventiva",
  "851": "Faturar Manutenção",
  "852": "Preventivo Interno",
  "853": "Contatar Cliente - Preventivo",
  "854": "Entregar Carnê",
  "855": "TV - Configurar MAC",
  "856": "CRT - Retrabalho Alteração WIFI",
  "857": "CRT - Pós Pesquisa Alteração WIFI",
  "858": "Cobrar Assinatura - Alteração de Plano",
  "859": "Retrabalho de Confirmação - Alteração de Plano",
  "860": "Processo de Contratação de SVA",
  "861": "Solicitar SVA",
  "862": "Confirmar IP Fixo - SVA",
  "863": "Adicionar IP Fixo - SVA",
  "864": "Cobrar Assinatura - SVA",
  "865": "Retrabalho de Solicitação - SVA",
  "866": "Faturar IP Fixo - SVA",
  "867": "Confirmar Aluguel - SVA",
  "868": "Instalar Equipamentos - SVA",
  "869": "Auditar Instalação - SVA",
  "870": "Faturar Aluguel - SVA",
  "871": "Retrabalho de Instalação - SVA",
  "872": "Retrabalho de Auditoria - SVA",
  "873": "Retrabalho de Auditoria - Alteração de Plano",
  "874": "Desativar Contrato - Exclusão SPC",
  "875": "Retrabalho de Auditoria - Mudança de Endereço",
  "876": "Processo de Devolução de Valor",
  "877": "Solicitar Devolução - Devolução de Valor",
  "878": "Devolver Valor",
  "879": "Enviar Comprovante - Devolução",
  "880": "Retrabalho de Solicitação - Devolução",
  "881": "CRT - Manutenção",
  "884": "Chamado técnico - Manutenção",
  "885": "Retrabalho Chamado técnico - Manutenção",
  "888": "CRT - Falha",
  "889": "Chamado técnico - Falha",
  "890": "Retrabalho Chamado técnico - Falha",
  "891": "MANUTENÇÃO - CRT - UPSUPPORT",
  "892": "Suporte Nível 3 - Manutenção",
  "893": "Suporte Nível 3 - Falha",
  "894": "FALHA - CRT - UPSUPPORT",
  "895": "Retrabalho de Auditoria - Suporte/Manutenção",
  "896": "Refazer Termo - Ativação",
  "897": "Retrabalho de Contagem - Rede Neutra",
  "898": "CRT - Auditoria Supervisão",
  "899": "CRT - Atendimento Auditoria",
  "900": "Chamado técnico - Auditoria CRT",
  "901": "Retrabalho Chamado técnico - Auditoria CRT",
  "902": "CRT - Pós Pesquisa Atendimento Auditoria",
  "904": "Contagem de Estoque",
  "905": "Retrabalho de Auditoria - Cancelamento",
  "906": "CRT - Correção Atendimento",
  "907": "CRT - Auditoria Correção Atendimento",
  "908": "CRT - Retrabalho Correção Atendimento",
  "909": "TEL - Faturar Alteração de Plano",
  "910": "TEL - Retrabalho de Confirmação - Alteração Plano",
  "911": "TEL - Remover Configurações - Cancelamento TEL",
  "912": "Processo de Cancelamento de SVA",
  "913": "Reverter Cancelamento SVA",
  "914": "Faturar Cancelamento SVA",
  "915": "Remover IP Fixo - Cancelamento SVA",
  "916": "Retrabalho de Reversão - Cancelamento SVA",
  "917": "Processo de Cancelamento de SVA - Aluguel",
  "918": "Retirar Equipamentos - Cancelamento SVA",
  "919": "Auditar Retirada - Cancelamento SVA",
  "920": "Cobrar Equipamentos - Cancelamento SVA",
  "921": "Faturar Equipamentos - Cancelamento SVA",
  "922": "Retrabalho de Retirada - Cancelamento SVA",
  "923": "Retrabalho de Cobrança - Cancelamento SVA",
  "924": "Negativar Contrato - Cancelamento SVA",
  "925": "Processo de Suspensão Temporária",
  "926": "Solicitar Suspensão",
  "927": "Confirmar Suspensão",
  "928": "Faturar Suspensão",
  "929": "Retrabalho de Solicitação - Suspensão",
  "930": "Retrabalho de Confirmação - Suspensão",
  "931": "Processo de Alteração de Plano",
  "932": "Solicitar Alteração de Plano",
  "933": "Confirmar Alteração de Plano",
  "934": "Faturar Alteração de Plano",
  "935": "Reter Cliente - Alteração de Plano",
  "936": "Retrabalho de Solicitação - Alteração de Plano",
  "937": "Auditar Alteração de Plano",
  "938": "Processo de TEL - Alteração de Plano",
  "939": "TEL - Solicitar Alteração de Plano",
  "940": "TEL - Confirmar Alteração de Plano",
  "941": "TEL - Retrabalho de Solicitação - Alteração Plano",
  "942": "Processo de Débito Automático",
  "943": "Solicitar Débito Automático",
  "944": "Confirmar Débito Automático",
  "945": "Faturar Débito Automático",
  "946": "Retrabalho de Solicitação - Débito Automático",
  "947": "Retrabalho de Confirmação - Débito Automático",
  "948": "Processo de Troca de Titularidade",
  "949": "Solicitar Troca de Titularidade",
  "950": "Confirmar Troca de Titularidade",
  "951": "Coletar Assinatura - Troca de Titularidade",
  "952": "Retrabalho de Solicitação - Troca de Titularidade",
  "953": "Faturar Troca de Titularidade",
  "954": "Retrabalho de Confirmação - Troca de Titularidade",
  "955": "Visita Técnica - Troca de Titularidade",
  "956": "Auditoria Técnica - Troca de Titularidade",
  "957": "Retrabalho Técnico - Troca de Titularidade",
  "958": "Acompanhar Pagamento - Troca de Titularidade",
  "959": "Processo de Mudança de Endereço",
  "960": "Contar Estoque",
  "961": "Analisar Estoque (Falta)",
  "962": "Efetuar Cobrança - Estoque",
  "963": "Analisar Estoque (Sobra)",
  "964": "Ajustar Falta - Estoque",
  "965": "Corrigir Falta - Estoque",
  "966": "Conferir Correção - Estoque",
  "967": "Retrabalho de Correção - Estoque",
  "968": "Ajustar Sobra - Estoque",
  "969": "Corrigir Sobra - Estoque",
  "970": "Processo de Contagem de Estoque",
  "971": "Analisar Estoque (Falta/Sobra)",
  "972": "Ajustar Falta/Sobra - Estoque",
  "973": "Corrigir Falta/Sobra - Estoque",
  "974": "Identificar Erro no Pagamento",
  "975": "Lançar Tarifa",
  "976": "Contatar Cliente - Erro Retorno",
  "977": "Corrigir Financeiro - Erro Retorno",
  "978": "Retrabalho de Solicitação - Erro Retorno",
  "979": "Devolver Valor - Erro Retorno",
  "980": "Enviar Comprovante - Erro Retorno",
  "981": "Processo de Correção de Erro no Retorno",
  "983": "TV - Reverter Cancelamento",
  "984": "TV - Faturar Cancelamento",
  "985": "Retrabalho de Reversão - TV Cancelamento",
  "986": "Processo de Cancelamento de TV",
  "987": "Processo de Retrabalho",
  "988": "Identificar Divergência - Retrabalho",
  "989": "Retrabalho Processual - Diversos",
  "990": "Conferir Correção - Retrabalho",
  "991": "TEL - Solicitar Troca de Atributo - Troca Titularidade",
  "992": "Solicitar Consulta - Consulta SPC",
  "993": "Consultar SPC",
  "994": "Revisar Consulta - SPC",
  "995": "Retornar Consulta - SPC",
  "996": "Retrabalho de Consulta - SPC",
  "997": "Processo de Consulta no SPC",
  "998": "Processo - Grupo Central Soluções em Cobranças",
  "999": "GCS - Revisar Contrato",
  "1000": "GCS - Acompanhar",
  "1001": "GCS - Faturar Financeiro",
  "1002": "GCS - Enviar Planilha",
  "1004": "GCS - Receber Repasse",
  "1005": "Processo de Devolução da Central",
  "1006": "GCS - Solicitar Devolução",
  "1007": "Retrabalho de Confirmação - Cancelamento",
  "1008": "Coletar Assinatura - Alteração de Plano",
  "1009": "Coletar Assinatura - Mudança de Endereço",
  "1010": "Coletar Assinatura - Troca de Titularidade",
  "1011": "Coletar Assinatura - Contratação de SVA",
  "1012": "TV - Coletar Assinatura - Alteração de Plano",
  "1013": "TV - Coletar Assinatura - Ativação",
  "1014": "Coletar Assinatura - Cobrança",
  "1015": "Coletar Assinatura - Suspensão Temporária",
  "1016": "Coletar Assinatura - Cancelamento",
  "1017": "Coletar Assinatura - Débito Automático",
  "1018": "Coletar Assinatura - Migração de Tecnologia",
  "1019": "TEL - Coletar Assinatura - Alteração de Plano",
  "1020": "TEL - Coletar Assinatura (Número Novo)",
  "1021": "TEL - Coletar Assinatura (Portabilidade)",
  "1022": "TEL - Coletar Assinatura - Portabilidade/TT",
  "1023": "Receber Pagamento - Suspensão Temporária",
  "1024": "TEL - Coletar Assinatura - Troca Titularidade TEL",
  "1025": "Processo de Envio de Cobrança para Assessoria",
  "1026": "Enviar para Édimo",
  "1027": "Enviar para Métrica",
  "1028": "Enviar para Central",
  "1029": "Negociar Inadimplência - Assessoria",
  "1030": "Cancelar Financeiro - Assessoria",
  "1031": "Excluir SPC - Assessoria",
  "1032": "Desativar Contrato - Assessoria",
  "1033": "Preparar Envio",
  "1034": "Faturar Inadimplência - Cobrança",
  "1035": "Confirmar Renegociação - Cobrança",
  "1036": "Confirmar Assinatura - Cobrança",
  "1037": "Faturar Renegociação - Cobrança",
  "1038": "Processo de Reativação",
  "1039": "Solicitar Reativação",
  "1040": "Confirmar Reativação",
  "1041": "Reativar Internet",
  "1042": "Coletar Assinatura - Reativação",
  "1043": "Retrabalho de Solicitação - Reativação",
  "1044": "Auditar Reativação",
  "1045": "Faturar Reativação",
  "1046": "Retrabalho de Reativação",
  "1047": "Reter Cliente - Reativação",
  "1048": "Retrabalho de Confirmação - Reativação",
  "1049": "Retrabalho de Auditoria - Reativação",
  "1050": "Desistir Pré-Contrato - Reativação",
  "1052": "Processo de Cobrança",
  "1053": "Negociar Inadimplência - Renegociação",
  "1054": "Confirmar Renegociação",
  "1055": "Confirmar Assinatura - Renegociação",
  "1056": "Coletar Assinatura - Renegociação",
  "1057": "Retrabalho de Renegociação",
  "1058": "Faturar Renegociação",
  "1059": "Retrabalho de Confirmação - Renegociação",
  "1060": "Processo de Renegociação",
  "1061": "Processo de Renegociação - Assessoria",
  "1062": "Renegociar Dívida",
  "1063": "Excluir do SPC",
  "1064": "Bloquear Contrato",
  "1065": "Desativar Contrato",
  "1066": "Retrabalho de Comprovante - Vendas",
  "1067": "TEL - Solicitar Cancelamento (Inadimplência)",
  "1068": "TEL - Solicitar Cancelamento",
  "1069": "TEL - Confirmar Assinatura",
  "1070": "TEL - Cadastrar Linha SIP",
  "1071": "Processo de Venda de Produtos",
  "1072": "Quitar Financeiro - Venda Produtos",
  "1073": "Retrabalho de Venda - Produtos",
  "1074": "TEL - Reter Cliente",
  "1075": "TEL - Coletar Assinatura",
  "1076": "TEL - Solicitar Portabilidade",
  "1077": "TEL - Solicitar Troca de Atributo",
  "1078": "Processo de Telefonia Digital",
  "1079": "TEL - Retrabalho da Solicitação",
  "1080": "Portabilidade Reprovada - Diversos",
  "1081": "TEL - Retrabalho de Confirmação",
  "1082": "Ativar Telefonia",
  "1083": "TEL - Retrabalho de Ativação",
  "1084": "TEL - Confirmar Assinatura - Alteração",
  "1085": "TEL - Alterar Plano",
  "1086": "Solicitar Portabilidade com TT - Vendas",
  "1087": "Retrabalho de Solicitação - Portabilidade/TT",
  "1088": "TEL - Confirmar Assinatura - Portabilidade/TT",
  "1089": "TEL - Solicitar Portabilidade - Portabilidade/TT",
  "1090": "Portabilidade Reprovada - Vendas",
  "1091": "TEL - Solicitar Troca de Atributo - Portabilidade/TT",
  "1092": "Reconectar Cliente",
  "1093": "Auditar Reconexão",
  "1094": "Retrabalho de Reconexão",
  "1095": "Faturar Reconexão",
  "1096": "Confirmar Assinatura - Suspensão",
  "1097": "Solicitar Migração - Tecnologia",
  "1098": "Confirmar Migração - Tecnologia",
  "1099": "Coletar Assinatura - Tecnologia",
  "1100": "Retrabalho de Solicitação - Tecnologia",
  "1101": "Confirmar Assinatura - Tecnologia",
  "1102": "Migrar Cliente - Tecnologia",
  "1103": "Auditar Migração - Tecnologia",
  "1104": "Reter Cliente - Tecnologia",
  "1105": "Retrabalho Técnico - Tecnologia",
  "1106": "Faturar Migração - Tecnologia",
  "1107": "Retirar Equipamentos - Tecnologia",
  "1108": "Auditar Retirada - Tecnologia",
  "1109": "Retrabalho de Retirada - Tecnologia",
  "1110": "Cobrar Equipamentos - Tecnologia",
  "1111": "Faturar Equipamentos - Tecnologia",
  "1112": "Retrabalho de Cobrança - Tecnologia",
  "1113": "Processo de Mudança de Tecnologia",
  "1114": "Solicitar PABX",
  "1115": "Confirmar Central PABX",
  "1116": "Confirmar Ramais",
  "1117": "Coletar Assinatura - PABX",
  "1118": "Retrabalho de Solicitação - PABX",
  "1119": "Confirmar Assinatura - PABX",
  "1120": "Configurar Central/PABX",
  "1121": "Ativar Central/PABX",
  "1122": "Auditar Ativação da Central/PABX",
  "1123": "Faturar Central/PABX",
  "1124": "Retrabalho de Ativação - PABX",
  "1125": "Retrabalho de Confirmação - PABX",
  "1126": "Processo de Central PABX",
  "1127": "Retrabalho de Negociação - Assessoria",
  "1128": "Processo de Cobrança",
  "1129": "Cobrança",
  "1130": "Quebrar Acordo",
  "1131": "Processo de Recebimento de Repasse",
  "1132": "Validar Repasse",
  "1133": "Receber Repasse da Édimo",
  "1134": "Receber Repasse da Métrica",
  "1135": "Receber Repasse da Conceito",
  "1136": "Receber Repasse da Wama",
  "1137": "Processo de Pedido de Devolução",
  "1138": "Validar Pedido de Devolução",
  "1139": "Solicitar Devolução Total",
  "1140": "Solicitar Devolução Parcial",
  "1141": "Retrabalho Processual - Devolução",
  "1143": "Baixar Comodatos",
  "1144": "Enviar para Wama",
  "1145": "Enviar para Conceito",
  "1146": "Cobrança de Renegociação",
  "1147": "Passo 3 - Negativação",
  "1148": "Cobrar Equipamentos - Cobrança",
  "1149": "TEL - Retrabalho de Auditoria",
  "1150": "Cancelar Nota Fiscal",
  "1151": "Corrigir Pagamento de Boleto",
  "1152": "Corrigir Pagamento Duplicado",
  "1153": "Analisar Pagamento",
  "1154": "Corrigir Financeiro",
  "1155": "Contatar Cliente - Retorno",
  "1156": "Entregar Carnê - Retorno",
  "1157": "Processo Gestão de Retorno",
  "1158": "Importado",
  "1159": "Emitir Nota Fiscal",
  "1160": "Enviar Nota Fiscal",
  "1161": "Retrabalho Processual - NF",
  "1162": "Processo de Assuntos Fiscais",
  "1163": "Assuntos Fiscais",
  "1164": "Retorno ao Cliente - Diversos",
  "1165": "Corrigir Pagamento de Boletos Futuros",
  "1166": "Retrabalho de Auditoria - Cancelamento",
  "1167": "Processo de Assuntos Telefônicos",
  "1168": "Assuntos Telefônicos",
  "1169": "Contatar Cliente - Telefônicos",
  "1170": "Incluir no SPC - Recuperação",
  "1171": "Auditar Nova Pré-Negativação",
  "1172": "Incluir no SPC - SPC",
  "1173": "Agendar Instalação - Vendas",
  "1174": "Agendar Instalação - Mudança Endereço",
  "1175": "Agendar Instalação - SVA",
  "1176": "Agendar Retirada - Cancelamento",
  "1177": "Agendar Retirada - SVA",
  "1178": "Agendar Visita - Alteração Plano",
  "1179": "Configurar Equipamento - Alteração Plano",
  "1180": "Retrabalho de Auditoria - Portabilidade/TT",
  "1181": "TEL - Receber Pagamento",
  "1182": "Retrabalho de Processo",
  "1183": "Retrabalho Técnico - Diversos",
  "1184": "Gerar Nota Fiscal - Rede Neutra",
  "1185": "Confirmar Assinatura - SVA",
  "1186": "Reverter Impossibilidade - SVA",
  "1187": "Retrabalho Processual - SVA",
  "1188": "Confirmar Assinatura - Alteração Plano",
  "1189": "Avaliar Equipamentos - Alteração Plano",
  "1190": "Instalar Equipamentos - Alteração Plano",
  "1191": "Retirar Equipamentos - Alteração Plano",
  "1192": "Conferência Operacional - Alteração Plano",
  "1193": "Retrabalho Processual - Alteração Plano",
  "1194": "Refazer Termos - Alteração Plano",
  "1195": "Faturar Materiais - Alteração Plano",
  "1196": "Processo de Contratação de SVA IP Fixo",
  "1197": "Processo de Contratação de SVA Aluguel",
  "1198": "Processo de Alteração de plano (Novo)",
  "1199": "Negociar Devoluções - Renegociação",
  "1200": "Faturar Renegociação - Devoluções",
  "1201": "Acompanhar Pagamento - Devoluções",
  "1202": "Retrabalho de Negociação - Devoluções",
  "1203": "Excluir no SPC - Devoluções",
  "1204": "Cancelar Renegociação - Devoluções",
  "1205": "Desativar Contrato - Devoluções",
  "1206": "Processo Renegociação das Devoluções",
  "1207": "Negociar Devoluções",
  "1208": "Avaliar Solicitação - Desconto",
  "1209": "Avaliação do Desconto",
  "1210": "Desconto Reprovado",
  "1211": "Ceder Desconto",
  "1212": "Retorno do Desconto",
  "1213": "Retrabalho de Avaliação - Supervisão",
  "1214": "Retrabalho de Avaliação - Atendimento",
  "1215": "Configurar IOT - SVA",
  "1216": "Retrabalho de Confirmar Assinatura - SVA",
  "1217": "Processo de Comissão",
  "1218": "Faturar Comissão",
  "1219": "Gerar Nota Fiscal - Comissão",
  "1220": "Acompanhar Pagamento - Diversos",
  "1221": "Processo de Atualização de E-mail",
  "1222": "Atualizar E-mail",
  "1223": "Solicitar SVA IP Fixo",
  "1224": "Confirmar Assinatura - SVA",
  "1225": "Retrabalho de Solicitação",
  "1226": "NÃO USAR - Processo Troca de Titularidade",
  "1227": "Solicitar Troca de Titularidade",
  "1228": "Faturar Troca de Titularidade",
  "1229": "Acompanhar Pagamento - Titularidade",
  "1230": "Retrabalho de Solicitação - Titularidade",
  "1231": "Confirmar Troca de Titularidade",
  "1232": "Cancelar Nota Fiscal - Titularidade",
  "1233": "Cancelar Financeiro - Titularidade",
  // IDs 658-846 adicionados (processos novos do banco externo)
  "658": "TEL - Faturar Equipamentos",
  "659": "Telefonia - Retrabalho de Cobrança",
  "662": "Auditoria de Remoção de CTO",
  "663": "Auditar Retirada - Mudança de Endereço",
  "664": "Auditar Mudança de Endereço",
  "665": "Reter Cliente - Mudança de Endereço",
  "666": "Cobrar Equipamentos - Mudança de Endereço",
  "667": "Faturar Equipamentos - Mudança de Endereço",
  "668": "Confirmar Mudança de Endereço",
  "669": "Mud Endereço - Executar Processo",
  "670": "Faturar Mudança de Endereço",
  "671": "Retrabalho de Confirmação - Mudança de Endereço",
  "672": "Mudar de Endereço",
  "673": "Mudança de Endereço (Rádio)",
  "674": "Remoção do Conector - Mudança de Endereço",
  "675": "Retirar Equipamentos - Mudança de Endereço",
  "676": "Retirada de Equipamentos (Rádio)",
  "677": "Retrabalho de Cobrança - Mudança de Endereço",
  "678": "Retrabalho de Retirada - Mudança de Endereço",
  "679": "Retrabalho de Solicitação - Mudança de Endereço",
  "680": "Retrabalho de Mudança",
  "681": "Solicitar Mudança de Endereço",
  "682": "Chamado técnico - CRT",
  "683": "Coletar Assinatura",
  "684": "Auditoria de Manutenção Correção de processo",
  "685": "Processo de Troca de Titularidade de Telefonia",
  "686": "TEL - Solicitar Troca de Titularidade",
  "687": "TEL - Retrabalho de Solicitação - Troca Titularidade",
  "688": "TEL - Consultar Consumo Excedente",
  "689": "TEL - Faturar Troca Titularidade",
  "690": "TEL - Confirmar Troca de Titularidade",
  "691": "TEL - Troca de Titularidade de Linha",
  "692": "TEL - Faturar Novo Titular",
  "693": "TEL - Visita Técnica - Troca Titularidade",
  "694": "TEL - Inativar Antigo Titular",
  "695": "TEL - Retrabalho de Confirmação - Troca Titularidade",
  "696": "TEL - Auditoria Técnica - Troca Titularidade",
  "697": "TEL - Retrabalho Técnico - Troca Titularidade",
  "698": "D-Cash - Validação de comissionamento",
  "699": "Confirmar Negociação - Cobrança",
  "700": "Retorno de Viabilidade (externo)",
  "701": "Configurar serviços adicionais Voip / PABX",
  "702": "Receber Pagamento - Cobrança",
  "703": "Auditar Inadimplência - Cobrança",
  "704": "Faturar Equipamentos - Cobrança",
  "706": "Cancelar Migração",
  "707": "Negociar com Indicado (Isenção)",
  "708": "Retorno da Indicação (Isenção)",
  "709": "Isentar Fidelidade (Indicação)",
  "710": "Telefonia - Consumo Excedente - Cancelamento",
  "711": "Telefonia - Retorno Excedente - Cancelamento",
  "712": "Analisar Contagem - Rede Neutra",
  "713": "Processo - Métrica Soluções",
  "714": "MET - Revisar Contrato",
  "715": "MET - Acompanhar",
  "716": "MET - Faturar Financeiro",
  "717": "MET - Enviar Planilha",
  "718": "Retorno de Excedente de Minutagem VOIP",
  "719": "Análise de Excedente de Minutagem VOIP",
  "720": "Processo de Cancelamento",
  "721": "Reversão de Cancelamento",
  "722": "Confirmar Cancelamento",
  "723": "Retrabalho de Reversão - Cancelamento",
  "724": "Faturar Cancelamento",
  "725": "Auditar Cancelamento",
  "726": "Retrabalho de Cancelamento",
  "727": "Retrabalho de Faturamento - Cancelamento",
  "728": "Incluir no SPC - Cancelamento",
  "729": "Negativar Contrato - Cancelamento",
  "730": "Retirada de Equipamentos - Cancelamento",
  "731": "Auditoria de Retirada - Cancelamento",
  "732": "Retrabalho de Retirada - Cancelamento",
  "733": "Cobrança de Equipamentos - Cancelamento",
  "734": "Faturar Equipamentos - Cancelamento",
  "735": "Retrabalho de Cobrança - Cancelamento",
  "736": "Nova Tentativa de Retirada - Cancelamento",
  "737": "Ceder Desconto (Reversão) - Cancelamento",
  "738": "Pesquisa Pós Retenção - Cancelamento",
  "739": "Suporte de Retenção - CRT - Cancelamento",
  "740": "Suporte de Retenção - Cancelamento",
  "741": "Auditoria Técnica de Suporte - Cancelamento",
  "742": "Retrabalho de Suporte - Cancelamento",
  "743": "Desativar Contrato - Cancelamento",
  "744": "Processo de Devolução da Métrica",
  "745": "MET - Solicitar Devolução",
  "746": "Solicitação de Contratação de Serviço Adicional",
  "747": "Contratar Rede Mesh",
  "748": "Retrabalho de Serviço Adicional",
  "749": "Instalar Rede Mesh",
  "750": "Faturamento de Rede Mesh",
  "751": "Processo de Exclusão no SPC",
  "752": "Processo de Inclusão no SPC",
  "753": "Auditar Pré-Negativação - Inclusão SPC",
  "754": "Retrabalho de Faturamento - Inclusão SPC",
  "755": "Auditoria Técnica - Serviços Adicionais",
  "756": "Processo de Portabilidade com Troca de Titularidade",
  "757": "TEL - Confirmar Portabilidade",
  "758": "Retrabalho de Solicitação - Portabilidade/TT",
  "759": "Configurar VoIP - Portabilidade/TT",
  "760": "Instalação de Telefonia - Portabilidade/TT",
  "761": "TEL - Faturar Portabilidade - Portabilidade/TT",
  "762": "Retrabalho de Confirmação - Portabilidade/TT",
  "763": "Solicitar Troca de Titularidade - Portabilidade",
  "764": "TEL - Auditoria de Instalação - Portabilidade/TT",
  "765": "Retrabalho de Instalação - Portabilidade/TT",
  "767": "MET - Receber Repasse",
  "768": "CRT - Manutenção/Falha",
  "769": "Chamado técnico - Manutenção/Falha",
  "770": "Retrabalho Chamado técnico - Manutenção/Falha",
  "771": "CRT - Retrabalho Manutenção/Falha",
  "772": "Auditoria de Infraestrutura",
  "773": "Negociação de Empreitada",
  "774": "Auditoria de Empreitada",
  "775": "Retrabalho de Empreitada",
  "776": "Passagem de Cabo",
  "777": "Auditoria de Passagem de Cabo",
  "778": "Retrabalho de Passagem de Cabo",
  "779": "Reverter Empreitada",
  "780": "Acompanhar Empreitada",
  "781": "Faturamento de Empreitada",
  "782": "Retrabalho de Contrato",
  "783": "Processo de Cancelamento por Inadimplência",
  "784": "Processo de Cancelamento de Telefonia por Inadimplência",
  "785": "Auditar Cancelamento - Inadimplência",
  "786": "Retrabalho de Faturamento - Inadimplência",
  "787": "Incluir no SPC - Inadimplência",
  "788": "Negativar Contrato - Inadimplência",
  "789": "Processo de Comprovante de Pagamento",
  "790": "Comprovante de Pagamento",
  "791": "Receber Pagamento - Comprovante",
  "792": "Retrabalho de Comprovante",
  "793": "Devolver Troca de Titularidade",
  "794": "Enviar Comprovante de Devolução",
  "795": "CS - Pesquisa pós atendimento CRT",
  "796": "CS - Pesquisa pós atendimento Upcall",
  "797": "Ativação de CTO / Ampliação de Portas",
  "798": "Renegociar Parcelamento - Inclusão SPC",
  "799": "Manutenção de Infraestrutura",
  "800": "Acompanhar Suspensão",
  "801": "Remover Suspensão",
  "802": "Remover Suspensão Antecipadamente",
  "803": "Entregar Carnê - Suspensão",
  "804": "Auditoria de Transferência Upcall",
  "805": "Agendar visita técnica - CRT",
  "806": "Boletim de Ocorrência - B.O.",
  "807": "CRT - Comercial",
  "808": "Processo Judicial",
  "809": "Faturar Taxa de Ativação",
  "810": "Coletar Assinatura - Vendas",
  "811": "Retrabalho de Auditoria - Ativação",
  "812": "Receber Pagamento - Ativação",
  "813": "Inviabilidade de Degustação",
  "814": "CRT - Link TV",
  "815": "CRT - TV Assistência",
  "816": "CRT - Retrabalho TV Assistência",
  "817": "CRT - Pós Pesquisa TV Assistência",
  "818": "Processo de Ativação (Televisão)",
  "819": "TV - Solicitar Ativação",
  "820": "TV - Confirmar Ativação",
  "821": "TV - Faturar Ativação",
  "822": "TV - Visita Técnica",
  "823": "TV - Cobrar Assinatura",
  "824": "Retrabalho de Solicitação - TV Ativação",
  "825": "TV - Auditar Visita",
  "826": "Retrabalho Técnico - TV",
  "827": "Retrabalho de Auditoria - TV Ativação",
};

// Função helper para obter o nome do assunto
export function getCategoriaName(id: string | number | null | undefined): string {
  if (!id) return "—";
  const idStr = String(id).trim();
  return categoriasMap[idStr] || `ID: ${idStr}`;
}
