import { Chamado } from "@/types/chamado";

export const mockChamados: Chamado[] = [
  {
    "ID Cliente": 302153,
    "Qtd. Chamados": 3,
    "Protocolo": "2025/35389",
    "Data de Abertura": "30/10/2025 12:09:33",
    "Última Atualização": "2025-10-30 12:09:33",
    "Responsável": "ANA LAENIA ALMEIDA ROCHA MOREIRA",
    "Setor": "Comercial",
    "Categoria": "Informações",
    "Motivo do Contato": "INSTALAÇÃO CAMERA MIBO",
    "Origem": "Atendimento On-Line",
    "Solicitante": "GERARDO OLIVEIRA FILHO",
    "Urgência": "Média",
    "Status": "Novo",
    "Dias desde Último Chamado": 1,
    "Tempo de Atendimento": "0h",
    "Classificação": "Reincidente",
    "Insight": "💡 Chamado ainda aberto | Cliente com vários chamados recentes | Reabriu em menos de 5 dias | Resolvido em poucas horas",
    "Chamados Anteriores": "1️⃣ Atualização de dados cadastro – 29/10/2025\n2️⃣ INFORMACOES CAMERA MIBO – 29/10/2025"
  },
  {
    "ID Cliente": 301245,
    "Qtd. Chamados": 5,
    "Protocolo": "2025/35390",
    "Data de Abertura": "29/10/2025 09:15:22",
    "Última Atualização": "2025-10-30 10:30:15",
    "Responsável": "CARLOS EDUARDO SANTOS",
    "Setor": "Técnico",
    "Categoria": "Suporte",
    "Motivo do Contato": "Lentidão na internet",
    "Origem": "Telefone",
    "Solicitante": "MARIA SILVA",
    "Urgência": "Alta",
    "Status": "Em Andamento",
    "Dias desde Último Chamado": 3,
    "Tempo de Atendimento": "25h",
    "Classificação": "Lento",
    "Insight": "⚠️ Chamado demorado | Cliente com múltiplas reclamações | Requer atenção urgente",
    "Chamados Anteriores": "1️⃣ Internet intermitente – 26/10/2025\n2️⃣ Sem conexão – 20/10/2025\n3️⃣ Velocidade baixa – 15/10/2025\n4️⃣ Problema no roteador – 10/10/2025"
  },
  {
    "ID Cliente": 303421,
    "Qtd. Chamados": 1,
    "Protocolo": "2025/35391",
    "Data de Abertura": "30/10/2025 14:30:10",
    "Última Atualização": "2025-10-30 15:45:20",
    "Responsável": "JULIA FERNANDES",
    "Setor": "Comercial",
    "Categoria": "Vendas",
    "Motivo do Contato": "Upgrade de plano",
    "Origem": "WhatsApp",
    "Solicitante": "JOÃO PEDRO",
    "Urgência": "Baixa",
    "Status": "Resolvido",
    "Dias desde Último Chamado": 0,
    "Tempo de Atendimento": "1h 15min",
    "Classificação": "Rápido",
    "Insight": "✅ Resolvido rapidamente | Primeira interação",
    "Chamados Anteriores": ""
  },
  {
    "ID Cliente": 300987,
    "Qtd. Chamados": 4,
    "Protocolo": "2025/35392",
    "Data de Abertura": "28/10/2025 16:20:45",
    "Última Atualização": "2025-10-30 11:10:33",
    "Responsável": "ROBERTO ALVES",
    "Setor": "Técnico",
    "Categoria": "Reparo",
    "Motivo do Contato": "Cabo rompido",
    "Origem": "Atendimento On-Line",
    "Solicitante": "ANA PAULA",
    "Urgência": "Alta",
    "Status": "Em Andamento",
    "Dias desde Último Chamado": 7,
    "Tempo de Atendimento": "43h",
    "Classificação": "Reincidente",
    "Insight": "💡 Cliente reincidente | Possível problema estrutural | Requer visita técnica",
    "Chamados Anteriores": "1️⃣ Queda frequente de sinal – 21/10/2025\n2️⃣ Internet oscilando – 14/10/2025\n3️⃣ Sem sinal – 05/10/2025"
  },
  {
    "ID Cliente": 302789,
    "Qtd. Chamados": 2,
    "Protocolo": "2025/35393",
    "Data de Abertura": "30/10/2025 08:45:12",
    "Última Atualização": "2025-10-30 09:20:50",
    "Responsável": "FERNANDA COSTA",
    "Setor": "Financeiro",
    "Categoria": "Cobrança",
    "Motivo do Contato": "Dúvida sobre fatura",
    "Origem": "E-mail",
    "Solicitante": "MARCOS ANTONIO",
    "Urgência": "Média",
    "Status": "Resolvido",
    "Dias desde Último Chamado": 15,
    "Tempo de Atendimento": "35min",
    "Classificação": "Rápido",
    "Insight": "✅ Resolvido em tempo hábil",
    "Chamados Anteriores": "1️⃣ Solicitação de segunda via – 15/10/2025"
  },
  {
    "ID Cliente": 301567,
    "Qtd. Chamados": 6,
    "Protocolo": "2025/35394",
    "Data de Abertura": "27/10/2025 13:10:22",
    "Última Atualização": "2025-10-30 08:30:15",
    "Responsável": "PATRICIA LIMA",
    "Setor": "Técnico",
    "Categoria": "Suporte",
    "Motivo do Contato": "Wi-Fi não conecta",
    "Origem": "Telefone",
    "Solicitante": "LUCIANA SOUZA",
    "Urgência": "Alta",
    "Status": "Novo",
    "Dias desde Último Chamado": 2,
    "Tempo de Atendimento": "0h",
    "Classificação": "Reincidente",
    "Insight": "⚠️ Múltiplas reclamações | Cliente insatisfeito | Requer atenção imediata",
    "Chamados Anteriores": "1️⃣ Senha Wi-Fi não funciona – 25/10/2025\n2️⃣ Rede não aparece – 22/10/2025\n3️⃣ Internet cai constantemente – 18/10/2025\n4️⃣ Problema no roteador – 12/10/2025\n5️⃣ Configuração Wi-Fi – 08/10/2025"
  },
  {
    "ID Cliente": 303012,
    "Qtd. Chamados": 1,
    "Protocolo": "2025/35395",
    "Data de Abertura": "30/10/2025 10:25:40",
    "Última Atualização": "2025-10-30 10:50:18",
    "Responsável": "DIEGO MARTINS",
    "Setor": "Comercial",
    "Categoria": "Informações",
    "Motivo do Contato": "Consulta de disponibilidade",
    "Origem": "WhatsApp",
    "Solicitante": "RAFAEL COSTA",
    "Urgência": "Baixa",
    "Status": "Resolvido",
    "Dias desde Último Chamado": 0,
    "Tempo de Atendimento": "25min",
    "Classificação": "Rápido",
    "Insight": "✅ Atendimento eficiente | Primeiro contato",
    "Chamados Anteriores": ""
  },
  {
    "ID Cliente": 300456,
    "Qtd. Chamados": 3,
    "Protocolo": "2025/35396",
    "Data de Abertura": "29/10/2025 15:40:33",
    "Última Atualização": "2025-10-30 14:20:45",
    "Responsável": "BRUNA OLIVEIRA",
    "Setor": "Técnico",
    "Categoria": "Instalação",
    "Motivo do Contato": "Reagendamento de visita",
    "Origem": "Atendimento On-Line",
    "Solicitante": "CLAUDIA REIS",
    "Urgência": "Média",
    "Status": "Em Andamento",
    "Dias desde Último Chamado": 4,
    "Tempo de Atendimento": "23h",
    "Classificação": "Normal",
    "Insight": "💡 Aguardando agendamento | Cliente solícito",
    "Chamados Anteriores": "1️⃣ Primeira tentativa de instalação – 25/10/2025\n2️⃣ Agendamento inicial – 20/10/2025"
  }
];
